// Edition 2023 defaults every singular scalar to explicit presence, which
// protoc-gen-go generates as *string. Every accessor here has to go through
// the getter to compile: the resource name, a reference, and the AIP-133
// create ID.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: editions/editions.proto

package editions

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gadget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Twin          *string                `protobuf:"bytes,2,opt,name=twin" json:"twin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gadget) Reset() {
	*x = Gadget{}
	mi := &file_editions_editions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gadget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gadget) ProtoMessage() {}

func (x *Gadget) ProtoReflect() protoreflect.Message {
	mi := &file_editions_editions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gadget.ProtoReflect.Descriptor instead.
func (*Gadget) Descriptor() ([]byte, []int) {
	return file_editions_editions_proto_rawDescGZIP(), []int{0}
}

func (x *Gadget) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Gadget) GetTwin() string {
	if x != nil && x.Twin != nil {
		return *x.Twin
	}
	return ""
}

type CreateGadgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gadget        *Gadget                `protobuf:"bytes,1,opt,name=gadget" json:"gadget,omitempty"`
	GadgetId      *string                `protobuf:"bytes,2,opt,name=gadget_id,json=gadgetId" json:"gadget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGadgetRequest) Reset() {
	*x = CreateGadgetRequest{}
	mi := &file_editions_editions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGadgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGadgetRequest) ProtoMessage() {}

func (x *CreateGadgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editions_editions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGadgetRequest.ProtoReflect.Descriptor instead.
func (*CreateGadgetRequest) Descriptor() ([]byte, []int) {
	return file_editions_editions_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGadgetRequest) GetGadget() *Gadget {
	if x != nil {
		return x.Gadget
	}
	return nil
}

func (x *CreateGadgetRequest) GetGadgetId() string {
	if x != nil && x.GadgetId != nil {
		return *x.GadgetId
	}
	return ""
}

// AIP-231 Batch Get: a repeated reference carries no single name to parse,
// so it generates nothing rather than failing generation.
type BatchGetGadgetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetGadgetsRequest) Reset() {
	*x = BatchGetGadgetsRequest{}
	mi := &file_editions_editions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetGadgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetGadgetsRequest) ProtoMessage() {}

func (x *BatchGetGadgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editions_editions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetGadgetsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetGadgetsRequest) Descriptor() ([]byte, []int) {
	return file_editions_editions_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetGadgetsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_editions_editions_proto protoreflect.FileDescriptor

const file_editions_editions_proto_rawDesc = "" +
	"\n" +
	"\x17editions/editions.proto\x12\x0etests.editions\x1a\x1bgoogle/api/field_info.proto\x1a\x19google/api/resource.proto\"t\n" +
	"\x06Gadget\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04twin\x18\x02 \x01(\tB\x17\xfaA\x14\n" +
	"\x12example.com/GadgetR\x04twin:)\xeaA&\n" +
	"\x12example.com/Gadget\x12\x10gadgets/{gadget}\"l\n" +
	"\x13CreateGadgetRequest\x12.\n" +
	"\x06gadget\x18\x01 \x01(\v2\x16.tests.editions.GadgetR\x06gadget\x12%\n" +
	"\tgadget_id\x18\x02 \x01(\tB\b\xe2\x8c\xcf\xd7\b\x02\b\x01R\bgadgetId\"G\n" +
	"\x16BatchGetGadgetsRequest\x12-\n" +
	"\x05names\x18\x01 \x03(\tB\x17\xfaA\x14\n" +
	"\x12example.com/GadgetR\x05namesBYZWgithub.com/protoc-contrib/protoc-gen-go-aip/internal/generator/resource/testpb/editionsb\beditionsp\xe8\a"

var (
	file_editions_editions_proto_rawDescOnce sync.Once
	file_editions_editions_proto_rawDescData []byte
)

func file_editions_editions_proto_rawDescGZIP() []byte {
	file_editions_editions_proto_rawDescOnce.Do(func() {
		file_editions_editions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_editions_editions_proto_rawDesc), len(file_editions_editions_proto_rawDesc)))
	})
	return file_editions_editions_proto_rawDescData
}

var file_editions_editions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_editions_editions_proto_goTypes = []any{
	(*Gadget)(nil),                 // 0: tests.editions.Gadget
	(*CreateGadgetRequest)(nil),    // 1: tests.editions.CreateGadgetRequest
	(*BatchGetGadgetsRequest)(nil), // 2: tests.editions.BatchGetGadgetsRequest
}
var file_editions_editions_proto_depIdxs = []int32{
	0, // 0: tests.editions.CreateGadgetRequest.gadget:type_name -> tests.editions.Gadget
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_editions_editions_proto_init() }
func file_editions_editions_proto_init() {
	if File_editions_editions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_editions_editions_proto_rawDesc), len(file_editions_editions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_editions_editions_proto_goTypes,
		DependencyIndexes: file_editions_editions_proto_depIdxs,
		MessageInfos:      file_editions_editions_proto_msgTypes,
	}.Build()
	File_editions_editions_proto = out.File
	file_editions_editions_proto_goTypes = nil
	file_editions_editions_proto_depIdxs = nil
}
