// Code generated by protoc-gen-go-aip. DO NOT EDIT.
// source: editions/editions.proto

package editions

import (
	fmt "fmt"
	uuid "github.com/google/uuid"
	strings "strings"
)

// GadgetName is the parsed form of a "example.com/Gadget" resource name (pattern "gadgets/{gadget}").
type GadgetName struct {
	GadgetID uuid.UUID
}

// ParseGadgetName parses s as GadgetName (pattern "gadgets/{gadget}").
func ParseGadgetName(s string) (GadgetName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return GadgetName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out GadgetName
	if parts[0] != "gadgets" {
		return GadgetName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "gadgets", parts[0])
	}
	if parts[1] == "" {
		return GadgetName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	v1, err := uuid.Parse(parts[1])
	if err != nil {
		return GadgetName{}, fmt.Errorf("parse %q: segment 1: %w", s, err)
	}
	out.GadgetID = v1
	return out, nil
}

// ParseFullGadgetName parses s as the fully-qualified form of GadgetName (prefix "//example.com/").
func ParseFullGadgetName(s string) (GadgetName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return GadgetName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseGadgetName(strings.TrimPrefix(s, "//example.com/"))
}

// String returns the relative resource name "gadgets/{gadget}" and implements fmt.Stringer.
func (n GadgetName) String() string {
	return "gadgets/" + n.GadgetID.String()
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n GadgetName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n GadgetName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative GadgetName.
func (n *GadgetName) UnmarshalText(b []byte) error {
	parsed, err := ParseGadgetName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// Validate returns an error if any variable segment is empty or contains '/'.
func (n GadgetName) Validate() error {
	if n.GadgetID == uuid.Nil {
		return fmt.Errorf("gadget: empty")
	}
	return nil
}

// Type returns the resource type "example.com/Gadget".
func (n GadgetName) Type() string {
	return "example.com/Gadget"
}

// Pattern returns the resource name pattern "gadgets/{gadget}".
func (n GadgetName) Pattern() string {
	return "gadgets/{gadget}"
}

// ContainsWildcard reports whether any variable segment is the AIP-159 wildcard "-".
func (n GadgetName) ContainsWildcard() bool {
	return false
}

// FormatGadgetName returns the relative resource name for a "example.com/Gadget" with the given id.
func FormatGadgetName(id uuid.UUID) string {
	return GadgetName{GadgetID: id}.String()
}

// ParseGadgetID parses s as GadgetName and returns its GadgetID field.
func ParseGadgetID(s string) (uuid.UUID, error) {
	parsed, err := ParseGadgetName(s)
	return parsed.GadgetID, err
}

// ParseName parses x.Name as GadgetName.
func (x *Gadget) ParseName() (GadgetName, error) {
	return ParseGadgetName(x.GetName())
}

// ParseFullName parses x.Name as GadgetName.
func (x *Gadget) ParseFullName() (GadgetName, error) {
	return ParseFullGadgetName(x.GetName())
}

// ParseTwin parses x.Twin as GadgetName.
func (x *Gadget) ParseTwin() (GadgetName, error) {
	return ParseGadgetName(x.GetTwin())
}

// ParseGadgetID returns the ID the caller proposed for the "example.com/Gadget"
// being created, or uuid.Nil when they left gadget_id empty.
//
// AIP-133: an empty gadget_id means the server assigns one, and which
// kind is the server's to decide — a version 7 UUID keeps an index in
// insertion order, a version 4 reveals nothing — so uuid.Nil is handed back
// for the caller to fill, e.g. with uuid.NewV7. The field holds a bare ID,
// not a resource name: build the name with GadgetName{GadgetID: id}.
func (x *CreateGadgetRequest) ParseGadgetID() (uuid.UUID, error) {
	id := x.GetGadgetId()
	if id == "" {
		return uuid.Nil, nil
	}
	parsed, err := uuid.Parse(id)
	if err != nil {
		return uuid.Nil, fmt.Errorf("parse gadget_id %q: %w", id, err)
	}
	if parsed == uuid.Nil {
		return uuid.Nil, fmt.Errorf("parse gadget_id %q: the nil UUID is not an ID", id)
	}
	return parsed, nil
}
