// Package fieldmask emits AIP-134 Validate() helpers on request messages
// that pair a google.protobuf.FieldMask with a single message-typed field
// (the resource being updated). The generated method delegates to
// go.einride.tech/aip/fieldmask.Validate, which checks every path resolves
// to a known field on the target message and accepts "*" only as the sole
// path.
package fieldmask

import (
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Suffix is `_aip.pb.fieldmask.go`. The leading `_` (0x5F) sorts after
// `.` (0x2E), so `<name>.pb.go` always initialises before our companion.
// The `_aip.` prefix groups all AIP-family plugin output together
// (`_aip.pb.resource.go`, `_aip.pb.query.go`, `_aip.pb.fieldmask.go`).
const generatedFilenameSuffix = "_aip.pb.fieldmask.go"

var fieldmaskPackage = protogen.GoImportPath("go.einride.tech/aip/fieldmask")

// Generate walks every file scheduled for generation and emits a
// `_aip.pb.fieldmask.go` companion for each file that contains at least
// one message matching the AIP-134 update-request shape.
func Generate(plugin *protogen.Plugin) error {
	for _, f := range plugin.Files {
		if !f.Generate {
			continue
		}
		generateFile(plugin, f)
	}
	return nil
}

// candidate captures the two fields the generated Validate() method
// needs to reference: the FieldMask and the message-typed resource it
// validates against.
type candidate struct {
	owner  *protogen.Message
	mask   *protogen.Field
	target *protogen.Field
}

func generateFile(plugin *protogen.Plugin, f *protogen.File) {
	var candidates []candidate
	walk(f.Messages, func(m *protogen.Message) {
		if c, ok := match(m); ok {
			candidates = append(candidates, c)
		}
	})
	if len(candidates) == 0 {
		return
	}

	g := plugin.NewGeneratedFile(
		f.GeneratedFilenamePrefix+generatedFilenameSuffix,
		f.GoImportPath,
	)
	g.P("// Code generated by protoc-gen-go-aip. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()

	for _, c := range candidates {
		emitValidate(g, c)
	}
}

// walk recursively visits every message in msgs and every nested message
// inside them. Mirrors the recursion in resource/generator.go.
func walk(msgs []*protogen.Message, visit func(*protogen.Message)) {
	for _, m := range msgs {
		visit(m)
		walk(m.Messages, visit)
	}
}

// match reports whether m has the AIP-134 update-request shape:
// exactly one singular FieldMask field and exactly one other singular
// message-typed field. Map entries are skipped — protogen surfaces them
// as messages but they're never user-facing requests.
func match(m *protogen.Message) (candidate, bool) {
	if m.Desc.IsMapEntry() {
		return candidate{}, false
	}
	var (
		mask, target           *protogen.Field
		maskCount, targetCount int
	)
	for _, field := range m.Fields {
		if field.Desc.Kind() != protoreflect.MessageKind {
			continue
		}
		if field.Desc.IsList() || field.Desc.IsMap() {
			continue
		}
		if field.Message.Desc.FullName() == "google.protobuf.FieldMask" {
			mask = field
			maskCount++
			continue
		}
		target = field
		targetCount++
	}
	if maskCount != 1 || targetCount != 1 {
		return candidate{}, false
	}
	return candidate{owner: m, mask: mask, target: target}, true
}

func emitValidate(g *protogen.GeneratedFile, c candidate) {
	owner := c.owner.GoIdent.GoName
	maskGo := c.mask.GoName
	targetGo := c.target.GoName
	targetType := c.target.Message.GoIdent.GoName

	g.P("// Validate returns an error if ", maskGo, " contains a path that does not")
	g.P("// resolve to a field on ", targetType, ". A nil mask is valid (full")
	g.P(`// replacement); "*" is valid only as the sole path.`)
	g.P("func (x *", owner, ") Validate() error {")
	g.P("	return ", fieldmaskPackage.Ident("Validate"), "(x.", maskGo, ", x.", targetGo, ")")
	g.P("}")
	g.P()
}
