package fieldmask_test

import (
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/protoc-contrib/protoc-gen-go-aip/internal/generator/fieldmask"
	testpb "github.com/protoc-contrib/protoc-gen-go-aip/internal/generator/fieldmask/testpb"
)

func runGenerator(files ...protoreflect.FileDescriptor) (*pluginpb.CodeGeneratorResponse, error) {
	req := &pluginpb.CodeGeneratorRequest{}
	seen := map[string]bool{}
	var walk func(fd protoreflect.FileDescriptor)
	walk = func(fd protoreflect.FileDescriptor) {
		if seen[fd.Path()] {
			return
		}
		seen[fd.Path()] = true
		imports := fd.Imports()
		for i := 0; i < imports.Len(); i++ {
			walk(imports.Get(i).FileDescriptor)
		}
		req.ProtoFile = append(req.ProtoFile, protodesc.ToFileDescriptorProto(fd))
	}
	for _, fd := range files {
		walk(fd)
		req.FileToGenerate = append(req.FileToGenerate, fd.Path())
	}
	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		return nil, err
	}
	if err := fieldmask.Generate(plugin); err != nil {
		return nil, err
	}
	return plugin.Response(), nil
}

func fileByName(resp *pluginpb.CodeGeneratorResponse, suffix string) string {
	for _, f := range resp.File {
		if strings.HasSuffix(f.GetName(), suffix) {
			return f.GetContent()
		}
	}
	return ""
}

var _ = Describe("fieldmask.Generate", func() {
	It("emits Validate() on UpdateBookRequest (canonical AIP-134 shape)", func() {
		resp, err := runGenerator(testpb.File_fieldmask_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "fieldmask_aip.pb.fieldmask.go")
		Expect(out).NotTo(BeEmpty())
		Expect(out).To(ContainSubstring("// Code generated by protoc-gen-go-aip. DO NOT EDIT."))
		Expect(out).To(ContainSubstring("package testpb"))
		Expect(out).To(ContainSubstring("func (x *UpdateBookRequest) Validate() error"))
		Expect(out).To(ContainSubstring("fieldmask.Validate(x.UpdateMask, x.Book)"))
	})

	It("emits Validate() regardless of field naming (PatchBookRequest uses target/mask)", func() {
		resp, err := runGenerator(testpb.File_fieldmask_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "fieldmask_aip.pb.fieldmask.go")
		Expect(out).To(ContainSubstring("func (x *PatchBookRequest) Validate() error"))
		Expect(out).To(ContainSubstring("fieldmask.Validate(x.Mask, x.Target)"))
	})

	It("does not emit Validate() on requests without a target message field", func() {
		resp, err := runGenerator(testpb.File_fieldmask_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "fieldmask_aip.pb.fieldmask.go")
		Expect(out).NotTo(ContainSubstring("GetBookRequest"))
	})

	It("does not emit Validate() when the target is ambiguous (multiple message fields)", func() {
		resp, err := runGenerator(testpb.File_fieldmask_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "fieldmask_aip.pb.fieldmask.go")
		Expect(out).NotTo(ContainSubstring("WeirdRequest"))
	})

	It("does not emit Validate() on messages without a FieldMask field", func() {
		resp, err := runGenerator(testpb.File_fieldmask_proto)
		Expect(err).NotTo(HaveOccurred())

		out := fileByName(resp, "fieldmask_aip.pb.fieldmask.go")
		Expect(out).NotTo(ContainSubstring("NoMaskRequest"))
	})

	It("emits no companion file when the proto has no qualifying messages", func() {
		// Re-running the generator on the same fixture twice should be
		// stable; the suite above asserts the produced content. This case
		// guards the empty-file path: zero candidates → no file.
		resp, err := runGenerator()
		Expect(err).NotTo(HaveOccurred())
		Expect(resp.File).To(BeEmpty())
	})
})
