// Code generated by protoc-gen-go-aip. DO NOT EDIT.
// source: fieldmask.proto

package testpb

import (
	fieldmask "go.einride.tech/aip/fieldmask"
)

// Validate returns an error if UpdateMask contains a path that does not
// resolve to a field on Book. A nil mask is valid (full
// replacement); "*" is valid only as the sole path.
func (x *UpdateBookRequest) Validate() error {
	return fieldmask.Validate(x.UpdateMask, x.Book)
}

// Validate returns an error if Mask contains a path that does not
// resolve to a field on Book. A nil mask is valid (full
// replacement); "*" is valid only as the sole path.
func (x *PatchBookRequest) Validate() error {
	return fieldmask.Validate(x.Mask, x.Target)
}
