// Test fixture for protoc-gen-go-aip fieldmask pass. Each request
// message exercises a different branch of the detector:
//
//   - UpdateBookRequest: AIP-134 shape (Book + FieldMask) — Validate() emitted.
//   - PatchBookRequest:  same shape with non-conventional naming — emitted.
//   - GetBookRequest:    read_mask but no message field — skipped.
//   - WeirdRequest:      two non-mask message fields — ambiguous, skipped.
//   - NoMaskRequest:     message field but no FieldMask — skipped.
//
// Regenerate with `buf generate` from the repo root.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: fieldmask.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	ReadCount     int64                  `protobuf:"varint,4,opt,name=read_count,json=readCount,proto3" json:"read_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_fieldmask_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetReadCount() int64 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

// UpdateBookRequest is the canonical AIP-134 shape: a single Book field
// paired with a single update_mask. Validate() is emitted.
type UpdateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_fieldmask_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *UpdateBookRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// PatchBookRequest exercises non-conventional naming — the resource field
// is `target` and the mask is `mask`. Detection is structural, so
// Validate() is still emitted.
type PatchBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Book                  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Mask          *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchBookRequest) Reset() {
	*x = PatchBookRequest{}
	mi := &file_fieldmask_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchBookRequest) ProtoMessage() {}

func (x *PatchBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchBookRequest.ProtoReflect.Descriptor instead.
func (*PatchBookRequest) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{2}
}

func (x *PatchBookRequest) GetTarget() *Book {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PatchBookRequest) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

// GetBookRequest carries a read_mask but no embedded message — there is
// nothing to validate the mask against, so Validate() is not emitted.
type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_fieldmask_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{3}
}

func (x *GetBookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBookRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// WeirdRequest has two non-mask message fields, so the target is
// ambiguous. Validate() is not emitted.
type WeirdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *Book                  `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             *Book                  `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	Mask          *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeirdRequest) Reset() {
	*x = WeirdRequest{}
	mi := &file_fieldmask_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeirdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeirdRequest) ProtoMessage() {}

func (x *WeirdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeirdRequest.ProtoReflect.Descriptor instead.
func (*WeirdRequest) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{4}
}

func (x *WeirdRequest) GetA() *Book {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *WeirdRequest) GetB() *Book {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *WeirdRequest) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

// NoMaskRequest has a message field but no FieldMask. Validate() is not
// emitted.
type NoMaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoMaskRequest) Reset() {
	*x = NoMaskRequest{}
	mi := &file_fieldmask_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoMaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoMaskRequest) ProtoMessage() {}

func (x *NoMaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmask_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoMaskRequest.ProtoReflect.Descriptor instead.
func (*NoMaskRequest) Descriptor() ([]byte, []int) {
	return file_fieldmask_proto_rawDescGZIP(), []int{5}
}

func (x *NoMaskRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

var File_fieldmask_proto protoreflect.FileDescriptor

const file_fieldmask_proto_rawDesc = "" +
	"\n" +
	"\x0ffieldmask.proto\x12\x06testpb\x1a google/protobuf/field_mask.proto\"g\n" +
	"\x04Book\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x1d\n" +
	"\n" +
	"read_count\x18\x04 \x01(\x03R\treadCount\"r\n" +
	"\x11UpdateBookRequest\x12 \n" +
	"\x04book\x18\x01 \x01(\v2\f.testpb.BookR\x04book\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"h\n" +
	"\x10PatchBookRequest\x12$\n" +
	"\x06target\x18\x01 \x01(\v2\f.testpb.BookR\x06target\x12.\n" +
	"\x04mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\"]\n" +
	"\x0eGetBookRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\breadMask\"v\n" +
	"\fWeirdRequest\x12\x1a\n" +
	"\x01a\x18\x01 \x01(\v2\f.testpb.BookR\x01a\x12\x1a\n" +
	"\x01b\x18\x02 \x01(\v2\f.testpb.BookR\x01b\x12.\n" +
	"\x04mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\"1\n" +
	"\rNoMaskRequest\x12 \n" +
	"\x04book\x18\x01 \x01(\v2\f.testpb.BookR\x04bookBXZVgithub.com/protoc-contrib/protoc-gen-go-aip/internal/generator/fieldmask/testpb;testpbb\x06proto3"

var (
	file_fieldmask_proto_rawDescOnce sync.Once
	file_fieldmask_proto_rawDescData []byte
)

func file_fieldmask_proto_rawDescGZIP() []byte {
	file_fieldmask_proto_rawDescOnce.Do(func() {
		file_fieldmask_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fieldmask_proto_rawDesc), len(file_fieldmask_proto_rawDesc)))
	})
	return file_fieldmask_proto_rawDescData
}

var file_fieldmask_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fieldmask_proto_goTypes = []any{
	(*Book)(nil),                  // 0: testpb.Book
	(*UpdateBookRequest)(nil),     // 1: testpb.UpdateBookRequest
	(*PatchBookRequest)(nil),      // 2: testpb.PatchBookRequest
	(*GetBookRequest)(nil),        // 3: testpb.GetBookRequest
	(*WeirdRequest)(nil),          // 4: testpb.WeirdRequest
	(*NoMaskRequest)(nil),         // 5: testpb.NoMaskRequest
	(*fieldmaskpb.FieldMask)(nil), // 6: google.protobuf.FieldMask
}
var file_fieldmask_proto_depIdxs = []int32{
	0, // 0: testpb.UpdateBookRequest.book:type_name -> testpb.Book
	6, // 1: testpb.UpdateBookRequest.update_mask:type_name -> google.protobuf.FieldMask
	0, // 2: testpb.PatchBookRequest.target:type_name -> testpb.Book
	6, // 3: testpb.PatchBookRequest.mask:type_name -> google.protobuf.FieldMask
	6, // 4: testpb.GetBookRequest.read_mask:type_name -> google.protobuf.FieldMask
	0, // 5: testpb.WeirdRequest.a:type_name -> testpb.Book
	0, // 6: testpb.WeirdRequest.b:type_name -> testpb.Book
	6, // 7: testpb.WeirdRequest.mask:type_name -> google.protobuf.FieldMask
	0, // 8: testpb.NoMaskRequest.book:type_name -> testpb.Book
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_fieldmask_proto_init() }
func file_fieldmask_proto_init() {
	if File_fieldmask_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fieldmask_proto_rawDesc), len(file_fieldmask_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fieldmask_proto_goTypes,
		DependencyIndexes: file_fieldmask_proto_depIdxs,
		MessageInfos:      file_fieldmask_proto_msgTypes,
	}.Build()
	File_fieldmask_proto = out.File
	file_fieldmask_proto_goTypes = nil
	file_fieldmask_proto_depIdxs = nil
}
