// Code generated by protoc-gen-go-aip. DO NOT EDIT.
// source: reference/reference.proto

package reference

import (
	fmt "fmt"
	external "github.com/protoc-contrib/protoc-gen-go-aip/internal/generator/resource/testpb/external"
	simple "github.com/protoc-contrib/protoc-gen-go-aip/internal/generator/resource/testpb/simple"
	strings "strings"
)

// FooName is the parsed form of a "example.com/Foo" resource name (pattern "foos/{foo}").
type FooName struct {
	FooID string
}

// ParseFooName parses s as FooName (pattern "foos/{foo}").
func ParseFooName(s string) (FooName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return FooName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out FooName
	if parts[0] != "foos" {
		return FooName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "foos", parts[0])
	}
	if parts[1] == "" {
		return FooName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.FooID = parts[1]
	return out, nil
}

// ParseFullFooName parses s as the fully-qualified form of FooName (prefix "//example.com/").
func ParseFullFooName(s string) (FooName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return FooName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseFooName(strings.TrimPrefix(s, "//example.com/"))
}

// String returns the relative resource name "foos/{foo}" and implements fmt.Stringer.
func (n FooName) String() string {
	return "foos/" + n.FooID
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n FooName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n FooName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative FooName.
func (n *FooName) UnmarshalText(b []byte) error {
	parsed, err := ParseFooName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// Validate returns an error if any variable segment is empty or contains '/'.
func (n FooName) Validate() error {
	if n.FooID == "" {
		return fmt.Errorf("foo: empty")
	}
	if strings.IndexByte(n.FooID, '/') != -1 {
		return fmt.Errorf("foo: contains illegal character '/'")
	}
	return nil
}

// Type returns the resource type "example.com/Foo".
func (n FooName) Type() string {
	return "example.com/Foo"
}

// Pattern returns the resource name pattern "foos/{foo}".
func (n FooName) Pattern() string {
	return "foos/{foo}"
}

// ContainsWildcard reports whether any variable segment is the AIP-159 wildcard "-".
func (n FooName) ContainsWildcard() bool {
	return n.FooID == "-"
}

// BarName is the parsed form of a "example.com/Bar" resource name (pattern "bars/{bar}").
type BarName struct {
	BarID string
}

// ParseBarName parses s as BarName (pattern "bars/{bar}").
func ParseBarName(s string) (BarName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return BarName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out BarName
	if parts[0] != "bars" {
		return BarName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "bars", parts[0])
	}
	if parts[1] == "" {
		return BarName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.BarID = parts[1]
	return out, nil
}

// ParseFullBarName parses s as the fully-qualified form of BarName (prefix "//example.com/").
func ParseFullBarName(s string) (BarName, error) {
	if !strings.HasPrefix(s, "//example.com/") {
		return BarName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//example.com/")
	}
	return ParseBarName(strings.TrimPrefix(s, "//example.com/"))
}

// String returns the relative resource name "bars/{bar}" and implements fmt.Stringer.
func (n BarName) String() string {
	return "bars/" + n.BarID
}

// FullName returns the fully-qualified resource name prefixed with "//example.com/".
func (n BarName) FullName() string {
	return "//example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n BarName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative BarName.
func (n *BarName) UnmarshalText(b []byte) error {
	parsed, err := ParseBarName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// Validate returns an error if any variable segment is empty or contains '/'.
func (n BarName) Validate() error {
	if n.BarID == "" {
		return fmt.Errorf("bar: empty")
	}
	if strings.IndexByte(n.BarID, '/') != -1 {
		return fmt.Errorf("bar: contains illegal character '/'")
	}
	return nil
}

// Type returns the resource type "example.com/Bar".
func (n BarName) Type() string {
	return "example.com/Bar"
}

// Pattern returns the resource name pattern "bars/{bar}".
func (n BarName) Pattern() string {
	return "bars/{bar}"
}

// ContainsWildcard reports whether any variable segment is the AIP-159 wildcard "-".
func (n BarName) ContainsWildcard() bool {
	return n.BarID == "-"
}

// ParseName parses x.Name as FooName.
func (x *Foo) ParseName() (FooName, error) {
	return ParseFooName(x.Name)
}

// ParseFullName parses x.Name as FooName.
func (x *Foo) ParseFullName() (FooName, error) {
	return ParseFullFooName(x.Name)
}

// ParseBar parses x.Bar as BarName.
func (x *Foo) ParseBar() (BarName, error) {
	return ParseBarName(x.Bar)
}

// ParseName parses x.Name as BarName.
func (x *Bar) ParseName() (BarName, error) {
	return ParseBarName(x.Name)
}

// ParseFullName parses x.Name as BarName.
func (x *Bar) ParseFullName() (BarName, error) {
	return ParseFullBarName(x.Name)
}

// ParseFoo parses x.Foo as FooName.
func (x *Bar) ParseFoo() (FooName, error) {
	return ParseFooName(x.Foo)
}

// ParseThingName parses x.ThingName as ThingName.
func (x *CrossPackage) ParseThingName() (simple.ThingName, error) {
	return simple.ParseThingName(x.ThingName)
}

// ParseExternalName parses x.ExternalName as ExternalName.
func (x *CrossPackageExternal) ParseExternalName() (external.ExternalName, error) {
	return external.ParseExternalName(x.ExternalName)
}
