// Code generated by protoc-gen-go-aip. DO NOT EDIT.
// source: test.proto

package testpb

import (
	fmt "fmt"
	strings "strings"
)

// BookName is the parsed form of a "testpb/Book" resource name (pattern "books/{book}").
type BookName struct {
	BookID string
}

// ParseBookName parses s as BookName (pattern "books/{book}").
func ParseBookName(s string) (BookName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return BookName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out BookName
	if parts[0] != "books" {
		return BookName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "books", parts[0])
	}
	if parts[1] == "" {
		return BookName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.BookID = parts[1]
	return out, nil
}

// ParseFullBookName parses s as the fully-qualified form of BookName (prefix "//testpb/").
func ParseFullBookName(s string) (BookName, error) {
	if !strings.HasPrefix(s, "//testpb/") {
		return BookName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//testpb/")
	}
	return ParseBookName(strings.TrimPrefix(s, "//testpb/"))
}

// String returns the relative resource name "books/{book}" and implements fmt.Stringer.
func (n BookName) String() string {
	return "books/" + n.BookID
}

// FullName returns the fully-qualified resource name prefixed with "//testpb/".
func (n BookName) FullName() string {
	return "//testpb/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n BookName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative BookName.
func (n *BookName) UnmarshalText(b []byte) error {
	parsed, err := ParseBookName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// Validate returns an error if any variable segment is empty or contains '/'.
func (n BookName) Validate() error {
	if n.BookID == "" {
		return fmt.Errorf("book: empty")
	}
	if strings.IndexByte(n.BookID, '/') != -1 {
		return fmt.Errorf("book: contains illegal character '/'")
	}
	return nil
}

// Type returns the resource type "testpb/Book".
func (n BookName) Type() string {
	return "testpb/Book"
}

// Pattern returns the resource name pattern "books/{book}".
func (n BookName) Pattern() string {
	return "books/{book}"
}

// ContainsWildcard reports whether any variable segment is the AIP-159 wildcard "-".
func (n BookName) ContainsWildcard() bool {
	return n.BookID == "-"
}

// ParseName parses x.Name as BookName.
func (x *Book) ParseName() (BookName, error) {
	return ParseBookName(x.Name)
}

// ParseFullName parses x.Name as BookName.
func (x *Book) ParseFullName() (BookName, error) {
	return ParseFullBookName(x.Name)
}
