// Code generated by protoc-gen-go-aip. DO NOT EDIT.
// source: internal/generator/testpb/test.proto

package testpb

import (
	fmt "fmt"
	filtering "go.einride.tech/aip/filtering"
	ordering "go.einride.tech/aip/ordering"
	pagination "go.einride.tech/aip/pagination"
)

// Query bundles the parsed AIP dimensions for a List request.
// A field is the zero value when the corresponding input was empty
// on the inbound request, or when the request does not support that
// dimension.
type Query struct {
	Filter    filtering.Filter
	OrderBy   ordering.OrderBy
	PageToken pagination.PageToken
}

// OrderByPaths returns the field paths from Query.OrderBy in their
// original order, suitable for building a fieldmaskpb.FieldMask or
// driving projection logic.
func (q Query) OrderByPaths() []string {
	paths := make([]string, len(q.OrderBy.Fields))
	for i, field := range q.OrderBy.Fields {
		paths[i] = field.Path
	}
	return paths
}

// ParseQuery parses every AIP dimension supported by ListBooksRequest,
// applying the same validation as the per-dimension parsers. On
// error the first failing dimension's wrapped error is returned
// verbatim; map to codes.InvalidArgument at the RPC boundary.
func (x *ListBooksRequest) ParseQuery() (Query, error) {
	filter, err := x.ParseFilter()
	if err != nil {
		return Query{}, err
	}
	order, err := x.ParseOrderBy()
	if err != nil {
		return Query{}, err
	}
	pageToken, err := x.ParsePageToken()
	if err != nil {
		return Query{}, err
	}
	return Query{
		Filter:    filter,
		OrderBy:   order,
		PageToken: pageToken,
	}, nil
}

// BookColumns maps proto field names on Book to their backing DB
// column names, for fields annotated `(protoc_contrib.aip.column) = "..."`.
// Fields without the annotation are absent from the map; callers should
// fall back to the proto field name in that case.
var BookColumns = map[string]string{
	"create_time": "created_at",
}

// BookFilterDeclarations is the AIP-160 CEL declaration set for
// fields declared `(protoc_contrib.aip.filterable) = true` on Book.
var BookFilterDeclarations *filtering.Declarations

func init() {
	decls, err := filtering.NewDeclarations(
		filtering.DeclareStandardFunctions(),
		filtering.DeclareIdent("title", filtering.TypeString),
		filtering.DeclareIdent("author", filtering.TypeString),
		filtering.DeclareIdent("read_count", filtering.TypeInt),
		filtering.DeclareIdent("published", filtering.TypeBool),
		filtering.DeclareIdent("genre", filtering.TypeEnum(Genre(0).Type())),
		filtering.DeclareIdent("create_time", filtering.TypeTimestamp),
	)
	if err != nil {
		panic(fmt.Errorf("protoc-gen-go-aip: Book declarations: %w", err))
	}
	BookFilterDeclarations = decls
}

// ParseFilter parses the AIP-160 `filter` string on ListBooksRequest against
// [BookFilterDeclarations]. The returned error is suitable for
// a connect InvalidArgument response; on success the caller receives the
// parsed [filtering.Filter], ready to translate into a WHERE clause.
func (x *ListBooksRequest) ParseFilter() (filtering.Filter, error) {
	filter, err := filtering.ParseFilter(x, BookFilterDeclarations)
	if err != nil {
		return filtering.Filter{}, fmt.Errorf("invalid filter: %w", err)
	}
	return filter, nil
}

// BookOrderByFields lists the AIP orderable paths on Book,
// in proto declaration order. Use [BookColumns] to resolve a
// path to its backing DB column name.
var BookOrderByFields = []string{
	"title",
	"create_time",
}

// ParseOrderBy parses the AIP-132 `order_by` string on ListBooksRequest.
// Rejects paths not in [BookOrderByFields]. The returned error
// is suitable for a connect InvalidArgument response; on success the
// caller receives the parsed [ordering.OrderBy], ready to translate
// into an ORDER BY clause.
func (x *ListBooksRequest) ParseOrderBy() (ordering.OrderBy, error) {
	order, err := ordering.ParseOrderBy(x)
	if err != nil {
		return ordering.OrderBy{}, fmt.Errorf("invalid order_by: %w", err)
	}
	if err := order.ValidateForMessage(&Book{}); err != nil {
		return ordering.OrderBy{}, fmt.Errorf("invalid order_by: %w", err)
	}
	if err := order.ValidateForPaths(BookOrderByFields...); err != nil {
		return ordering.OrderBy{}, fmt.Errorf("invalid order_by: %w", err)
	}
	return order, nil
}

// ParsePageToken decodes the AIP-158 offset `page_token` on ListBooksRequest
// and verifies its checksum against the current request, delegating to
// [pagination.ParsePageToken]. On the first page (page_token == "") it
// returns a zero-offset [pagination.PageToken] carrying the current checksum.
func (x *ListBooksRequest) ParsePageToken() (pagination.PageToken, error) {
	pageToken, err := pagination.ParsePageToken(x)
	if err != nil {
		return pagination.PageToken{}, fmt.Errorf("invalid page_token: %w", err)
	}
	return pageToken, nil
}
