// Test fixture for protoc-gen-go-aip-query. The Book resource exercises both
// AIP-132 orderable fields (title, create_time) and AIP-160 filterable
// fields (title as TypeString, author as TypeString, read_count as
// TypeInt, published as TypeBool, genre as TypeEnum, create_time as
// TypeTimestamp). ListBooksRequest + ListBooksResponse drive the
// request/response discovery convention.
//
// Regenerate: remove the internal/generator/testpb exclude from buf.yaml,
// run `buf generate`, restore the exclude.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/generator/testpb/test.proto

package testpb

import (
	_ "github.com/protoc-contrib/protoc-gen-go-aip/protoc_contrib/aip"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genre int32

const (
	Genre_GENRE_UNSPECIFIED Genre = 0
	Genre_GENRE_FICTION     Genre = 1
	Genre_GENRE_NONFICTION  Genre = 2
)

// Enum value maps for Genre.
var (
	Genre_name = map[int32]string{
		0: "GENRE_UNSPECIFIED",
		1: "GENRE_FICTION",
		2: "GENRE_NONFICTION",
	}
	Genre_value = map[string]int32{
		"GENRE_UNSPECIFIED": 0,
		"GENRE_FICTION":     1,
		"GENRE_NONFICTION":  2,
	}
)

func (x Genre) Enum() *Genre {
	p := new(Genre)
	*p = x
	return p
}

func (x Genre) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Genre) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_generator_testpb_test_proto_enumTypes[0].Descriptor()
}

func (Genre) Type() protoreflect.EnumType {
	return &file_internal_generator_testpb_test_proto_enumTypes[0]
}

func (x Genre) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Genre.Descriptor instead.
func (Genre) EnumDescriptor() ([]byte, []int) {
	return file_internal_generator_testpb_test_proto_rawDescGZIP(), []int{0}
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	ReadCount     int64                  `protobuf:"varint,4,opt,name=read_count,json=readCount,proto3" json:"read_count,omitempty"`
	Published     bool                   `protobuf:"varint,5,opt,name=published,proto3" json:"published,omitempty"`
	Genre         Genre                  `protobuf:"varint,6,opt,name=genre,proto3,enum=testpb.Genre" json:"genre,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_internal_generator_testpb_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_internal_generator_testpb_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_internal_generator_testpb_test_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetReadCount() int64 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

func (x *Book) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

func (x *Book) GetGenre() Genre {
	if x != nil {
		return x.Genre
	}
	return Genre_GENRE_UNSPECIFIED
}

func (x *Book) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type ListBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksRequest) Reset() {
	*x = ListBooksRequest{}
	mi := &file_internal_generator_testpb_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRequest) ProtoMessage() {}

func (x *ListBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_generator_testpb_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksRequest.ProtoReflect.Descriptor instead.
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return file_internal_generator_testpb_test_proto_rawDescGZIP(), []int{1}
}

func (x *ListBooksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBooksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListBooksRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListBooksRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksResponse) Reset() {
	*x = ListBooksResponse{}
	mi := &file_internal_generator_testpb_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksResponse) ProtoMessage() {}

func (x *ListBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_generator_testpb_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksResponse.ProtoReflect.Descriptor instead.
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return file_internal_generator_testpb_test_proto_rawDescGZIP(), []int{2}
}

func (x *ListBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *ListBooksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_internal_generator_testpb_test_proto protoreflect.FileDescriptor

const file_internal_generator_testpb_test_proto_rawDesc = "" +
	"\n" +
	"$internal/generator/testpb/test.proto\x12\x06testpb\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eprotoc_contrib/aip/query.proto\"\xce\x02\n" +
	"\x04Book\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\x05title\x18\x02 \x01(\tB\b\x88\xb5\x18\x01\x90\xb5\x18\x01R\x05title\x12\x1c\n" +
	"\x06author\x18\x03 \x01(\tB\x04\x90\xb5\x18\x01R\x06author\x12#\n" +
	"\n" +
	"read_count\x18\x04 \x01(\x03B\x04\x90\xb5\x18\x01R\treadCount\x12\"\n" +
	"\tpublished\x18\x05 \x01(\bB\x04\x90\xb5\x18\x01R\tpublished\x12)\n" +
	"\x05genre\x18\x06 \x01(\x0e2\r.testpb.GenreB\x04\x90\xb5\x18\x01R\x05genre\x12S\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x16\x88\xb5\x18\x01\x90\xb5\x18\x01\x9a\xb5\x18\n" +
	"created_atR\n" +
	"createTime:+\xeaA(\n" +
	"\vtestpb/Book\x12\fbooks/{book}*\x05books2\x04book\"\x81\x01\n" +
	"\x10ListBooksRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"_\n" +
	"\x11ListBooksResponse\x12\"\n" +
	"\x05books\x18\x01 \x03(\v2\f.testpb.BookR\x05books\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*G\n" +
	"\x05Genre\x12\x15\n" +
	"\x11GENRE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rGENRE_FICTION\x10\x01\x12\x14\n" +
	"\x10GENRE_NONFICTION\x10\x02BTZRgithub.com/protoc-contrib/protoc-gen-go-aip-query/internal/generator/testpb;testpbb\x06proto3"

var (
	file_internal_generator_testpb_test_proto_rawDescOnce sync.Once
	file_internal_generator_testpb_test_proto_rawDescData []byte
)

func file_internal_generator_testpb_test_proto_rawDescGZIP() []byte {
	file_internal_generator_testpb_test_proto_rawDescOnce.Do(func() {
		file_internal_generator_testpb_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_generator_testpb_test_proto_rawDesc), len(file_internal_generator_testpb_test_proto_rawDesc)))
	})
	return file_internal_generator_testpb_test_proto_rawDescData
}

var file_internal_generator_testpb_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_generator_testpb_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_generator_testpb_test_proto_goTypes = []any{
	(Genre)(0),                    // 0: testpb.Genre
	(*Book)(nil),                  // 1: testpb.Book
	(*ListBooksRequest)(nil),      // 2: testpb.ListBooksRequest
	(*ListBooksResponse)(nil),     // 3: testpb.ListBooksResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_internal_generator_testpb_test_proto_depIdxs = []int32{
	0, // 0: testpb.Book.genre:type_name -> testpb.Genre
	4, // 1: testpb.Book.create_time:type_name -> google.protobuf.Timestamp
	1, // 2: testpb.ListBooksResponse.books:type_name -> testpb.Book
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_generator_testpb_test_proto_init() }
func file_internal_generator_testpb_test_proto_init() {
	if File_internal_generator_testpb_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_generator_testpb_test_proto_rawDesc), len(file_internal_generator_testpb_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_generator_testpb_test_proto_goTypes,
		DependencyIndexes: file_internal_generator_testpb_test_proto_depIdxs,
		EnumInfos:         file_internal_generator_testpb_test_proto_enumTypes,
		MessageInfos:      file_internal_generator_testpb_test_proto_msgTypes,
	}.Build()
	File_internal_generator_testpb_test_proto = out.File
	file_internal_generator_testpb_test_proto_goTypes = nil
	file_internal_generator_testpb_test_proto_depIdxs = nil
}
