// Code generated by protoc-gen-go-aip. DO NOT EDIT.
// source: test.proto

package testpb

import (
	cel "cel.dev/cel-go/cel"
	fmt "fmt"
	strings "strings"
)

// ListBooksFilterEnv is the CEL environment used to compile `filter`
// expressions on ListBooksRequest. It declares every field of
// Book that has a CEL type; which of them a client may
// actually query is gated by the column map at the query layer.
//
// It has no macros and no optional syntax: `exists`, `has` and the like
// would expand to comprehensions and presence tests, and `a.?b` to an
// optional, none of which has a reading as a query.
var ListBooksFilterEnv *cel.Env

func init() {
	env, err := cel.NewEnv(
		cel.ClearMacros(),
		cel.Variable("name", cel.StringType),
		cel.Variable("title", cel.StringType),
		cel.Variable("author", cel.StringType),
		cel.Variable("read_count", cel.IntType),
		cel.Variable("published", cel.BoolType),
		cel.Variable("genre", cel.IntType),
		cel.Variable("create_time", cel.TimestampType),
	)
	if err != nil {
		panic(fmt.Errorf("protoc-gen-go-aip: ListBooks filter env: %w", err))
	}
	ListBooksFilterEnv = env
}

// ParseFilter compiles the CEL `filter` expression on ListBooksRequest against
// [ListBooksFilterEnv] and rejects one that does not evaluate to bool.
// It returns (nil, nil) when no filter was provided, a blank one included.
// The returned error is suitable for a connect InvalidArgument response;
// the *cel.Ast can be passed straight to pgxcel.Where.
func (x *ListBooksRequest) ParseFilter() (*cel.Ast, error) {
	if strings.TrimSpace(x.GetFilter()) == "" {
		return nil, nil
	}
	ast, issues := ListBooksFilterEnv.Compile(x.GetFilter())
	if err := issues.Err(); err != nil {
		return nil, fmt.Errorf("invalid filter: %w", err)
	}
	// A filter is a predicate; anything else would only fail further down,
	// in the query layer or the database, with a less clear error.
	if !ast.OutputType().IsExactType(cel.BoolType) {
		return nil, fmt.Errorf("invalid filter: must evaluate to bool, got %s", ast.OutputType())
	}
	return ast, nil
}
