// Code generated by protoc-gen-go-aip. DO NOT EDIT.
// source: versions/v1/library.proto

package v1

import (
	fmt "fmt"
	strings "strings"
)

// ShelfName is the parsed form of a "versions.example.com/Shelf" resource name (pattern "shelves/{shelf}").
type ShelfName struct {
	ShelfID string
}

// ParseShelfName parses s as ShelfName (pattern "shelves/{shelf}").
func ParseShelfName(s string) (ShelfName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 2 {
		return ShelfName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(parts))
	}
	var out ShelfName
	if parts[0] != "shelves" {
		return ShelfName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "shelves", parts[0])
	}
	if parts[1] == "" {
		return ShelfName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.ShelfID = parts[1]
	return out, nil
}

// ParseFullShelfName parses s as the fully-qualified form of ShelfName (prefix "//versions.example.com/").
func ParseFullShelfName(s string) (ShelfName, error) {
	if !strings.HasPrefix(s, "//versions.example.com/") {
		return ShelfName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//versions.example.com/")
	}
	return ParseShelfName(strings.TrimPrefix(s, "//versions.example.com/"))
}

// String returns the relative resource name "shelves/{shelf}" and implements fmt.Stringer.
func (n ShelfName) String() string {
	return "shelves/" + n.ShelfID
}

// FullName returns the fully-qualified resource name prefixed with "//versions.example.com/".
func (n ShelfName) FullName() string {
	return "//versions.example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n ShelfName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative ShelfName.
func (n *ShelfName) UnmarshalText(b []byte) error {
	parsed, err := ParseShelfName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// Validate returns an error if any variable segment is empty or contains '/'.
func (n ShelfName) Validate() error {
	if n.ShelfID == "" {
		return fmt.Errorf("shelf: empty")
	}
	if strings.IndexByte(n.ShelfID, '/') != -1 {
		return fmt.Errorf("shelf: contains illegal character '/'")
	}
	return nil
}

// Type returns the resource type "versions.example.com/Shelf".
func (n ShelfName) Type() string {
	return "versions.example.com/Shelf"
}

// Pattern returns the resource name pattern "shelves/{shelf}".
func (n ShelfName) Pattern() string {
	return "shelves/{shelf}"
}

// ContainsWildcard reports whether any variable segment is the AIP-159 wildcard "-".
func (n ShelfName) ContainsWildcard() bool {
	return n.ShelfID == "-"
}

// BookName is the parsed form of a "versions.example.com/Book" resource name (pattern "shelves/{shelf}/books/{book}").
type BookName struct {
	ShelfID string
	BookID  string
}

// ParseBookName parses s as BookName (pattern "shelves/{shelf}/books/{book}").
func ParseBookName(s string) (BookName, error) {
	parts := strings.Split(s, "/")
	if len(parts) != 4 {
		return BookName{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(parts))
	}
	var out BookName
	if parts[0] != "shelves" {
		return BookName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "shelves", parts[0])
	}
	if parts[1] == "" {
		return BookName{}, fmt.Errorf("parse %q: empty value for segment 1", s)
	}
	out.ShelfID = parts[1]
	if parts[2] != "books" {
		return BookName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "books", parts[2])
	}
	if parts[3] == "" {
		return BookName{}, fmt.Errorf("parse %q: empty value for segment 3", s)
	}
	out.BookID = parts[3]
	return out, nil
}

// ParseFullBookName parses s as the fully-qualified form of BookName (prefix "//versions.example.com/").
func ParseFullBookName(s string) (BookName, error) {
	if !strings.HasPrefix(s, "//versions.example.com/") {
		return BookName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//versions.example.com/")
	}
	return ParseBookName(strings.TrimPrefix(s, "//versions.example.com/"))
}

// String returns the relative resource name "shelves/{shelf}/books/{book}" and implements fmt.Stringer.
func (n BookName) String() string {
	return "shelves/" + n.ShelfID + "/books/" + n.BookID
}

// FullName returns the fully-qualified resource name prefixed with "//versions.example.com/".
func (n BookName) FullName() string {
	return "//versions.example.com/" + n.String()
}

// MarshalText implements encoding.TextMarshaler and emits the relative resource name.
func (n BookName) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler by parsing b as a relative BookName.
func (n *BookName) UnmarshalText(b []byte) error {
	parsed, err := ParseBookName(string(b))
	if err != nil {
		return err
	}
	*n = parsed
	return nil
}

// Validate returns an error if any variable segment is empty or contains '/'.
func (n BookName) Validate() error {
	if n.ShelfID == "" {
		return fmt.Errorf("shelf: empty")
	}
	if strings.IndexByte(n.ShelfID, '/') != -1 {
		return fmt.Errorf("shelf: contains illegal character '/'")
	}
	if n.BookID == "" {
		return fmt.Errorf("book: empty")
	}
	if strings.IndexByte(n.BookID, '/') != -1 {
		return fmt.Errorf("book: contains illegal character '/'")
	}
	return nil
}

// Type returns the resource type "versions.example.com/Book".
func (n BookName) Type() string {
	return "versions.example.com/Book"
}

// Pattern returns the resource name pattern "shelves/{shelf}/books/{book}".
func (n BookName) Pattern() string {
	return "shelves/{shelf}/books/{book}"
}

// ContainsWildcard reports whether any variable segment is the AIP-159 wildcard "-".
func (n BookName) ContainsWildcard() bool {
	return n.ShelfID == "-" || n.BookID == "-"
}

// Parent returns the parent ShelfName derived from this resource's fields.
func (n BookName) Parent() ShelfName {
	return ShelfName{
		ShelfID: n.ShelfID,
	}
}

// BookName builds a BookName under this ShelfName.
func (n ShelfName) BookName(
	bookID string,
) BookName {
	return BookName{
		ShelfID: n.ShelfID,
		BookID:  bookID,
	}
}

// ParseName parses x.Name as ShelfName.
func (x *Shelf) ParseName() (ShelfName, error) {
	return ParseShelfName(x.GetName())
}

// ParseFullName parses x.Name as ShelfName.
func (x *Shelf) ParseFullName() (ShelfName, error) {
	return ParseFullShelfName(x.GetName())
}

// ParseName parses x.Name as BookName.
func (x *Book) ParseName() (BookName, error) {
	return ParseBookName(x.GetName())
}

// ParseFullName parses x.Name as BookName.
func (x *Book) ParseFullName() (BookName, error) {
	return ParseFullBookName(x.GetName())
}

// ParseShelf parses x.Shelf as ShelfName.
func (x *Book) ParseShelf() (ShelfName, error) {
	return ParseShelfName(x.GetShelf())
}
