// Package generator emits ordering (AIP-132), pagination (AIP-158) and CEL
// filtering helpers on List request messages.
//
// A request is a List request when a service method takes it and returns a
// message with a single repeated message field; that field's type is the
// resource, and its fields are what the helpers expose. Nothing needs
// annotating — the same derivation the OpenAPI generator performs on a
// List*Response schema.
package query

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Suffix is `_aip.pb.query.go`. The leading `_` (0x5F) sorts after `.`
// (0x2E), so `<name>.pb.go` always initialises before our companion —
// descriptor init runs before `init()` references enum types. The
// `_aip.` prefix also groups all AIP-family plugin output together
// (`_aip.pb.resource.go`, etc.) regardless of the trailing suffix.
const generatedFilenameSuffix = "_aip.pb.query.go"

var (
	fmtPackage = protogen.GoImportPath("fmt")
	aipPackage = protogen.GoImportPath("github.com/protoc-contrib/aip-go")
	celPackage = protogen.GoImportPath("github.com/google/cel-go/cel")
)

// Generate walks every file scheduled for generation and emits a
// `_aip.pb.query.go` companion for each file containing at least one
// List request carrying a `filter` or `order_by` field.
func Generate(plugin *protogen.Plugin) error {
	for _, f := range plugin.Files {
		if !f.Generate {
			continue
		}
		if err := generateFile(plugin, f); err != nil {
			return err
		}
	}
	return nil
}

func generateFile(plugin *protogen.Plugin, f *protogen.File) error {
	resources := resourceByRequest(f)
	var requests []requestInfo
	for _, m := range f.Messages {
		info, err := analyzeRequest(m, resources[m])
		if err != nil {
			return fmt.Errorf("%s: %w", m.Desc.FullName(), err)
		}
		if info == nil {
			continue
		}
		requests = append(requests, *info)
	}
	if len(requests) == 0 {
		return nil
	}

	g := plugin.NewGeneratedFile(
		f.GeneratedFilenamePrefix+generatedFilenameSuffix,
		f.GoImportPath,
	)
	g.P("// Code generated by protoc-gen-go-aip. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()

	if anyQuery(requests) {
		filter, orderBy, pageToken := queryFields(requests)
		emitQueryType(g, filter, orderBy, pageToken)
	}

	for _, r := range requests {
		if r.dims() >= 2 {
			emitParseQuery(g, r)
		}
		if r.filter != nil {
			if err := emitFilterDeclarations(g, r); err != nil {
				return fmt.Errorf("%s: %w", r.request.GoIdent.GoName, err)
			}
			emitParseFilter(g, r)
		}
		if r.orderBy != nil {
			emitOrderByFields(g, r)
			emitParseOrderBy(g, r)
		}
		if r.hasPageToken {
			emitParsePageToken(g, r)
		}
	}
	return nil
}

type requestInfo struct {
	request      *protogen.Message
	filter       *filterAnalysis
	orderBy      *orderByAnalysis
	hasPageToken bool
}

type filterAnalysis struct {
	resource *protogen.Message
	fields   []*protogen.Field
}

type orderByAnalysis struct {
	resource *protogen.Message
	paths    []string
}

// dims counts how many of {filter, order_by, page_token} this request
// supports. ParseQuery is emitted only when >= 2.
func (r requestInfo) dims() int {
	n := 0
	if r.filter != nil {
		n++
	}
	if r.orderBy != nil {
		n++
	}
	if r.hasPageToken {
		n++
	}
	return n
}

// anyQuery reports whether any request has at least two of
// {filter, order_by, page_token} — the threshold for emitting a Query
// bundle and its ParseQuery method.
func anyQuery(requests []requestInfo) bool {
	for _, r := range requests {
		if r.dims() >= 2 {
			return true
		}
	}
	return false
}

// queryFields unions the dimensions present across all requests so the
// file-level Query type contains every field any ParseQuery needs to
// populate. Fields absent from a given request are left zero by that
// request's ParseQuery.
func queryFields(requests []requestInfo) (filter, orderBy, pageToken bool) {
	for _, r := range requests {
		if r.dims() < 2 {
			continue
		}
		if r.filter != nil {
			filter = true
		}
		if r.orderBy != nil {
			orderBy = true
		}
		if r.hasPageToken {
			pageToken = true
		}
	}
	return
}

// analyzeRequest inspects req for a `filter`
// or `order_by` field and structural pagination. Returns nil when
// neither dimension is annotated; pagination alone is not enough to opt
// in.
// analyzeRequest derives the queryable surface of req from resource — the
// message the corresponding List method returns.
//
// Every resource field that maps to a CEL type is declared; there is no
// per-request allow-list. The gate on what a client may actually filter or
// sort by is the AIP-path to DB-column map handed to the query layer, which
// is fail-closed and lives next to the schema that knows which columns exist
// and which are indexed. A second allow-list in the .proto would only be a
// copy of it, free to drift.
func analyzeRequest(req, resource *protogen.Message) (*requestInfo, error) {
	if resource == nil {
		return nil, nil
	}
	info := &requestInfo{request: req}
	for _, field := range req.Fields {
		if !isQueryStringField(field) {
			continue
		}
		switch string(field.Desc.Name()) {
		case "filter":
			fields, err := queryableFields(resource)
			if err != nil {
				return nil, fmt.Errorf("filter: %w", err)
			}
			if len(fields) == 0 {
				continue
			}
			info.filter = &filterAnalysis{resource: resource, fields: fields}
		case "order_by":
			fields, err := queryableFields(resource)
			if err != nil {
				return nil, fmt.Errorf("order_by: %w", err)
			}
			if len(fields) == 0 {
				continue
			}
			paths := make([]string, 0, len(fields))
			for _, f := range fields {
				paths = append(paths, string(f.Desc.Name()))
			}
			info.orderBy = &orderByAnalysis{resource: resource, paths: paths}
		}
	}
	if info.filter == nil && info.orderBy == nil {
		return nil, nil
	}
	info.hasPageToken = hasPaginationFields(req)
	return info, nil
}

// queryableFields returns the fields of resource that have a CEL type, in
// declaration order. Fields with no scalar reading — nested messages other
// than the well-known wrappers, repeated fields and maps — have no total
// order and cannot be compared, so they are skipped rather than rejected.
func queryableFields(resource *protogen.Message) ([]*protogen.Field, error) {
	fields := make([]*protogen.Field, 0, len(resource.Fields))
	for _, field := range resource.Fields {
		if field.Desc.IsList() || field.Desc.IsMap() {
			continue
		}
		if !hasCELType(field) {
			continue
		}
		fields = append(fields, field)
	}
	return fields, nil
}

// resourceByRequest maps each List request message to the resource its
// method returns, by taking the sole repeated message field of the response.
//
// This mirrors how the OpenAPI generator reads a List*Response schema, so
// both surfaces declare the same variables for the same resource.
func resourceByRequest(f *protogen.File) map[*protogen.Message]*protogen.Message {
	out := make(map[*protogen.Message]*protogen.Message)
	for _, service := range f.Services {
		for _, method := range service.Methods {
			if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
				continue
			}
			if resource := repeatedResourceOf(method.Output); resource != nil {
				out[method.Input] = resource
			}
		}
	}
	return out
}

// repeatedResourceOf returns the resource carried by a List response: its
// single repeated message field. A response with none, or with more than
// one, is not a List response and yields nil.
func repeatedResourceOf(response *protogen.Message) *protogen.Message {
	var found *protogen.Message
	for _, field := range response.Fields {
		if !field.Desc.IsList() || field.Message == nil || field.Desc.IsMap() {
			continue
		}
		if found != nil {
			return nil // ambiguous
		}
		found = field.Message
	}
	return found
}

func isQueryStringField(field *protogen.Field) bool {
	return field.Desc.Kind() == protoreflect.StringKind && !field.Desc.IsList()
}

// hasPaginationFields reports whether req satisfies
// aip.PageRequest structurally — a `string
// page_token` field and an `int32 page_size` field. Generated
// messages of such requests pick up the interface automatically,
// so pagination.ParsePageToken accepts them without further ceremony.
func hasPaginationFields(req *protogen.Message) bool {
	var hasToken, hasSize bool
	for _, field := range req.Fields {
		switch string(field.Desc.Name()) {
		case "page_token":
			if field.Desc.Kind() == protoreflect.StringKind && !field.Desc.IsList() {
				hasToken = true
			}
		case "page_size":
			if field.Desc.Kind() == protoreflect.Int32Kind && !field.Desc.IsList() {
				hasSize = true
			}
		}
	}
	return hasToken && hasSize
}

// prefixOf strips the conventional `Request` suffix to produce the
// per-request identifier prefix (e.g. `ListBooksRequest` →
// `ListBooks`). Falls back to the full Go name when absent.
func prefixOf(req *protogen.Message) string {
	return strings.TrimSuffix(req.GoIdent.GoName, "Request")
}

// emitFilterDeclarations emits a package-level `{Request}FilterDeclarations`
// var plus an `init()` that builds it exactly once at package load. Any
// error from NewDeclarations is a codegen bug (duplicate idents, bad CEL
// types) and is raised as a panic so it surfaces at program start, not on
// first request.
func emitFilterDeclarations(g *protogen.GeneratedFile, r requestInfo) error {
	prefix := prefixOf(r.request)

	type decl struct {
		name string
		kind string
	}
	var decls []decl
	for _, field := range r.filter.fields {
		kind, err := celTypeExpr(g, field)
		if err != nil {
			return fmt.Errorf("field %q: %w", field.Desc.Name(), err)
		}
		decls = append(decls, decl{name: string(field.Desc.Name()), kind: kind})
	}

	g.P("// ", prefix, "FilterEnv is the CEL environment used to compile `filter`")
	g.P("// expressions on ", r.request.GoIdent.GoName, ". It declares every field of")
	g.P("// ", r.filter.resource.GoIdent.GoName, " that has a CEL type; which of them a client may")
	g.P("// actually query is gated by the column map at the query layer.")
	g.P("var ", prefix, "FilterEnv *", celPackage.Ident("Env"))
	g.P()
	g.P("func init() {")
	g.P("	env, err := ", celPackage.Ident("NewEnv"), "(")
	for _, d := range decls {
		g.P(`		`, celPackage.Ident("Variable"), `("`, d.name, `", `, d.kind, `),`)
	}
	g.P("	)")
	g.P("	if err != nil {")
	g.P(`		panic(`, fmtPackage.Ident("Errorf"), `("protoc-gen-go-aip: `, prefix, ` filter env: %w", err))`)
	g.P("	}")
	g.P("	", prefix, "FilterEnv = env")
	g.P("}")
	g.P()
	return nil
}

// emitOrderByFields emits a package-level `{Request}OrderByFields` slice
// listing the AIP orderable paths for the request, in declaration order.
// ParseOrderBy uses it as the allow-list.
func emitOrderByFields(g *protogen.GeneratedFile, r requestInfo) {
	prefix := prefixOf(r.request)
	g.P("// ", prefix, "OrderByFields lists the AIP orderable paths on ", r.request.GoIdent.GoName, ",")
	g.P("// in declaration order.")
	g.P("var ", prefix, "OrderByFields = []string{")
	for _, p := range r.orderBy.paths {
		g.P(`	"`, p, `",`)
	}
	g.P("}")
	g.P()
}

func emitParseFilter(g *protogen.GeneratedFile, r requestInfo) {
	reqName := r.request.GoIdent.GoName
	prefix := prefixOf(r.request)

	g.P("// ParseFilter compiles the CEL `filter` expression on ", reqName, " against")
	g.P("// [", prefix, "FilterEnv]. It returns (nil, nil) when no filter was")
	g.P("// provided. The returned error is suitable for a connect InvalidArgument")
	g.P("// response; the *cel.Ast can be passed straight to pgxcel.Transpile.")
	g.P("func (x *", reqName, ") ParseFilter() (*", celPackage.Ident("Ast"), ", error) {")
	g.P(`	if x.GetFilter() == "" {`)
	g.P("		return nil, nil")
	g.P("	}")
	g.P("	ast, issues := ", prefix, "FilterEnv.Compile(x.GetFilter())")
	g.P("	if err := issues.Err(); err != nil {")
	g.P(`		return nil, `, fmtPackage.Ident("Errorf"), `("invalid filter: %w", err)`)
	g.P("	}")
	g.P("	return ast, nil")
	g.P("}")
	g.P()
}

func emitParseOrderBy(g *protogen.GeneratedFile, r requestInfo) {
	reqName := r.request.GoIdent.GoName
	prefix := prefixOf(r.request)
	resIdent := r.orderBy.resource.GoIdent

	g.P("// ParseOrderBy parses the AIP-132 `order_by` string on ", reqName, ".")
	g.P("// Rejects paths not in [", prefix, "OrderByFields]. The returned error")
	g.P("// is suitable for a connect InvalidArgument response; on success the")
	g.P("// caller receives the parsed [", aipPackage.Ident("OrderBy"), "], ready to translate")
	g.P("// into an ORDER BY clause.")
	g.P("func (x *", reqName, ") ParseOrderBy() (", aipPackage.Ident("OrderBy"), ", error) {")
	g.P("	order, err := ", aipPackage.Ident("ParseOrderBy"), "(x)")
	g.P("	if err != nil {")
	g.P(`		return `, aipPackage.Ident("OrderBy"), `{}, `, fmtPackage.Ident("Errorf"), `("invalid order_by: %w", err)`)
	g.P("	}")
	g.P("	if err := order.ValidateForMessage(&", resIdent, "{}); err != nil {")
	g.P(`		return `, aipPackage.Ident("OrderBy"), `{}, `, fmtPackage.Ident("Errorf"), `("invalid order_by: %w", err)`)
	g.P("	}")
	g.P("	if err := order.ValidateForPaths(", prefix, "OrderByFields...); err != nil {")
	g.P(`		return `, aipPackage.Ident("OrderBy"), `{}, `, fmtPackage.Ident("Errorf"), `("invalid order_by: %w", err)`)
	g.P("	}")
	g.P("	return order, nil")
	g.P("}")
	g.P()
}

// emitQueryType emits a single package-level `Query` struct bundling the
// parsed dimensions a ParseQuery method returns. Declared once per
// generated file; the field set is the union across all requests that have
// at least two of {filter, order_by, page_token}. Dimensions a given
// request does not support are left zero by that request's ParseQuery.
func emitQueryType(g *protogen.GeneratedFile, filter, orderBy, pageToken bool) {
	g.P("// Query bundles the parsed AIP dimensions for a List request.")
	g.P("// A field is the zero value when the corresponding input was empty")
	g.P("// on the inbound request, or when the request does not support that")
	g.P("// dimension.")
	g.P("type Query struct {")
	if filter {
		g.P("	Filter    *", celPackage.Ident("Ast"))
	}
	if orderBy {
		g.P("	OrderBy   ", aipPackage.Ident("OrderBy"))
	}
	if pageToken {
		g.P("	PageToken ", aipPackage.Ident("PageToken"))
	}
	g.P("}")
	g.P()

	if orderBy {
		g.P("// OrderByPaths returns the field paths from Query.OrderBy in their")
		g.P("// original order, suitable for building a fieldmaskpb.FieldMask or")
		g.P("// driving projection logic.")
		g.P("func (q Query) OrderByPaths() []string {")
		g.P("	paths := make([]string, len(q.OrderBy.Fields))")
		g.P("	for i, field := range q.OrderBy.Fields {")
		g.P("		paths[i] = field.Path")
		g.P("	}")
		g.P("	return paths")
		g.P("}")
		g.P()
	}
}

// emitParseQuery emits a ParseQuery method that composes whichever of
// ParseFilter, ParseOrderBy, and ParsePageToken the request supports.
// The first failing dimension's error is returned verbatim, preserving
// its "invalid {dimension}" prefix for the caller to log or map.
func emitParseQuery(g *protogen.GeneratedFile, r requestInfo) {
	reqName := r.request.GoIdent.GoName
	hasFilter := r.filter != nil
	hasOrder := r.orderBy != nil
	hasToken := r.hasPageToken

	g.P("// ParseQuery parses every AIP dimension supported by ", reqName, ",")
	g.P("// applying the same validation as the per-dimension parsers. On")
	g.P("// error the first failing dimension's wrapped error is returned")
	g.P("// verbatim; map to codes.InvalidArgument at the RPC boundary.")
	g.P("func (x *", reqName, ") ParseQuery() (Query, error) {")
	if hasFilter {
		g.P("	filter, err := x.ParseFilter()")
		g.P("	if err != nil {")
		g.P("		return Query{}, err")
		g.P("	}")
	}
	if hasOrder {
		g.P("	order, err := x.ParseOrderBy()")
		g.P("	if err != nil {")
		g.P("		return Query{}, err")
		g.P("	}")
	}
	if hasToken {
		g.P("	pageToken, err := x.ParsePageToken()")
		g.P("	if err != nil {")
		g.P("		return Query{}, err")
		g.P("	}")
	}
	g.P("	return Query{")
	if hasFilter {
		g.P("		Filter:    filter,")
	}
	if hasOrder {
		g.P("		OrderBy:   order,")
	}
	if hasToken {
		g.P("		PageToken: pageToken,")
	}
	g.P("	}, nil")
	g.P("}")
	g.P()
}

// emitParsePageToken emits a thin forwarder onto pagination.ParsePageToken
// so callers get the same req.ParseXxx() ergonomic as ParseFilter /
// ParseOrderBy.
func emitParsePageToken(g *protogen.GeneratedFile, r requestInfo) {
	reqName := r.request.GoIdent.GoName

	g.P("// ParsePageToken decodes the AIP-158 offset `page_token` on ", reqName, "")
	g.P("// and verifies its checksum against the current request, delegating to")
	g.P("// [", aipPackage.Ident("ParsePageToken"), "]. On the first page (page_token == \"\") it")
	g.P("// returns a zero-offset [", aipPackage.Ident("PageToken"), "] carrying the current checksum.")
	g.P("func (x *", reqName, ") ParsePageToken() (", aipPackage.Ident("PageToken"), ", error) {")
	g.P("	pageToken, err := ", aipPackage.Ident("ParsePageToken"), "(x)")
	g.P("	if err != nil {")
	g.P(`		return `, aipPackage.Ident("PageToken"), `{}, `, fmtPackage.Ident("Errorf"), `("invalid page_token: %w", err)`)
	g.P("	}")
	g.P("	return pageToken, nil")
	g.P("}")
	g.P()
}

// celType returns the cel-go type identifier matching the field's proto
// kind, and whether the field has one at all.
//
// Fields with no total order — nested messages other than the well-known
// Timestamp and Duration, maps, and repeated fields — have none, and cannot
// appear in a filter or an order_by.
func celType(field *protogen.Field) (protogen.GoIdent, bool) {
	if field.Desc.IsList() || field.Desc.IsMap() {
		return protogen.GoIdent{}, false
	}
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		return celPackage.Ident("StringType"), true
	case protoreflect.BoolKind:
		return celPackage.Ident("BoolType"), true
	case protoreflect.Int32Kind, protoreflect.Int64Kind,
		protoreflect.Sint32Kind, protoreflect.Sint64Kind,
		protoreflect.Sfixed32Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.Fixed32Kind, protoreflect.Fixed64Kind:
		return celPackage.Ident("IntType"), true
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return celPackage.Ident("DoubleType"), true
	case protoreflect.EnumKind:
		// CEL models proto enums as integers, which is also how a database
		// column stores them, so an enum compares against its number.
		return celPackage.Ident("IntType"), true
	case protoreflect.MessageKind:
		switch string(field.Message.Desc.FullName()) {
		case "google.protobuf.Timestamp":
			return celPackage.Ident("TimestampType"), true
		case "google.protobuf.Duration":
			return celPackage.Ident("DurationType"), true
		}
	}
	return protogen.GoIdent{}, false
}

// hasCELType reports whether field can appear in a filter or an order_by.
func hasCELType(field *protogen.Field) bool {
	_, ok := celType(field)
	return ok
}

// celTypeExpr renders the cel.XxxType expression for field, qualified for
// the file being generated.
func celTypeExpr(g *protogen.GeneratedFile, field *protogen.Field) (string, error) {
	ident, ok := celType(field)
	if !ok {
		return "", fmt.Errorf("field %q has no CEL type", field.Desc.Name())
	}
	return g.QualifiedGoIdent(ident), nil
}
