// Package generator emits AIP-132 ordering and AIP-160 filtering helpers
// on `List{Resource}Request` messages, driven by
// `(protoc_contrib.aip.orderable)` / `(protoc_contrib.aip.filterable)`
// annotations on resource fields.
package query

import (
	"fmt"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"

	aippb "github.com/protoc-contrib/protoc-gen-go-aip/protoc_contrib/aip"
)

// Suffix is `_aip.pb.query.go`. The leading `_` (0x5F) sorts after `.`
// (0x2E), so `<name>.pb.go` always initialises before our companion —
// descriptor init runs before `init()` references enum types. The
// `_aip.` prefix also groups all AIP-family plugin output together
// (`_aip.pb.resource.go`, etc.) regardless of the trailing suffix.
const generatedFilenameSuffix = "_aip.pb.query.go"

var (
	fmtPackage        = protogen.GoImportPath("fmt")
	orderingPackage   = protogen.GoImportPath("go.einride.tech/aip/ordering")
	filteringPackage  = protogen.GoImportPath("go.einride.tech/aip/filtering")
	paginationPackage = protogen.GoImportPath("go.einride.tech/aip/pagination")
)

// Generate walks every file scheduled for generation and emits a
// `_aip.pb.query.go` companion for each file that contains at least one
// resource with AIP-annotated fields paired to a discoverable
// List{Resource}Request.
func Generate(plugin *protogen.Plugin) error {
	for _, f := range plugin.Files {
		if !f.Generate {
			continue
		}
		if err := generateFile(plugin, f); err != nil {
			return err
		}
	}
	return nil
}

func generateFile(plugin *protogen.Plugin, f *protogen.File) error {
	var pairs []listPair
	for _, m := range f.Messages {
		if !isResource(m) {
			continue
		}
		req := findListRequest(f, m)
		if req == nil {
			continue
		}
		orderable := collectFields(m, aippb.E_Orderable)
		filterable := collectFields(m, aippb.E_Filterable)
		if len(orderable) == 0 && len(filterable) == 0 {
			continue
		}
		pairs = append(pairs, listPair{
			resource:     m,
			request:      req,
			orderable:    orderable,
			filterable:   filterable,
			hasPageToken: hasPaginationFields(req),
		})
	}
	if len(pairs) == 0 {
		return nil
	}

	g := plugin.NewGeneratedFile(
		f.GeneratedFilenamePrefix+generatedFilenameSuffix,
		f.GoImportPath,
	)
	g.P("// Code generated by protoc-gen-go-aip. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()

	if anyQuery(pairs) {
		f, o, t := queryFields(pairs)
		emitQueryType(g, f, o, t)
	}

	for _, p := range pairs {
		if p.dims() >= 2 {
			emitParseQuery(g, p)
		}
		if len(p.filterable) > 0 {
			if err := emitFilterDeclarations(g, p); err != nil {
				return fmt.Errorf("%s: %w", p.resource.GoIdent.GoName, err)
			}
			emitParseFilter(g, p)
		}
		if len(p.orderable) > 0 {
			emitOrderByFields(g, p)
			emitParseOrderBy(g, p)
		}
		if p.hasPageToken {
			emitParsePageToken(g, p)
		}
	}
	return nil
}

// anyQuery reports whether any pair has at least two of
// {filter, order_by, page_token} — the threshold for emitting a Query
// bundle and its ParseQuery method.
func anyQuery(pairs []listPair) bool {
	for _, p := range pairs {
		if p.dims() >= 2 {
			return true
		}
	}
	return false
}

// queryFields unions the dimensions present across all pairs so the
// file-level Query type contains every field any ParseQuery needs to
// populate. Fields absent from a given pair are left zero by that
// pair's ParseQuery.
func queryFields(pairs []listPair) (filter, orderBy, pageToken bool) {
	for _, p := range pairs {
		if p.dims() < 2 {
			continue
		}
		if len(p.filterable) > 0 {
			filter = true
		}
		if len(p.orderable) > 0 {
			orderBy = true
		}
		if p.hasPageToken {
			pageToken = true
		}
	}
	return
}

type listPair struct {
	resource     *protogen.Message
	request      *protogen.Message
	orderable    []*protogen.Field
	filterable   []*protogen.Field
	hasPageToken bool
}

// dims counts how many of {filter, order_by, page_token} this pair
// supports. ParseQuery is emitted only when >= 2.
func (p listPair) dims() int {
	n := 0
	if len(p.filterable) > 0 {
		n++
	}
	if len(p.orderable) > 0 {
		n++
	}
	if p.hasPageToken {
		n++
	}
	return n
}

// hasPaginationFields reports whether req satisfies
// go.einride.tech/aip/pagination.Request structurally — a `string
// page_token` field and an `int32 page_size` field. Generated
// messages of such requests pick up the interface automatically,
// so pagination.ParsePageToken accepts them without further ceremony.
func hasPaginationFields(req *protogen.Message) bool {
	var hasToken, hasSize bool
	for _, field := range req.Fields {
		switch string(field.Desc.Name()) {
		case "page_token":
			if field.Desc.Kind() == protoreflect.StringKind && !field.Desc.IsList() {
				hasToken = true
			}
		case "page_size":
			if field.Desc.Kind() == protoreflect.Int32Kind && !field.Desc.IsList() {
				hasSize = true
			}
		}
	}
	return hasToken && hasSize
}

func isResource(m *protogen.Message) bool {
	opts, ok := m.Desc.Options().(*descriptorpb.MessageOptions)
	if !ok || opts == nil {
		return false
	}
	return proto.HasExtension(opts, annotations.E_Resource)
}

// collectFields returns the fields of m whose FieldOptions have the given
// bool extension set to true, preserving proto declaration order.
func collectFields(m *protogen.Message, ext protoreflect.ExtensionType) []*protogen.Field {
	var out []*protogen.Field
	for _, field := range m.Fields {
		opts, ok := field.Desc.Options().(*descriptorpb.FieldOptions)
		if !ok || opts == nil {
			continue
		}
		if !proto.HasExtension(opts, ext) {
			continue
		}
		v, ok := proto.GetExtension(opts, ext).(bool)
		if !ok || !v {
			continue
		}
		out = append(out, field)
	}
	return out
}

// findListRequest locates the `List{Plural}Request` sibling for a
// resource by scanning every `List*Response` in the same file for a
// `repeated {ResourceMessage}` field and flipping the `Response` suffix
// to `Request`. Returns nil when no unambiguous match exists.
func findListRequest(f *protogen.File, res *protogen.Message) *protogen.Message {
	for _, resp := range f.Messages {
		name := string(resp.Desc.Name())
		if !strings.HasPrefix(name, "List") || !strings.HasSuffix(name, "Response") {
			continue
		}
		if !hasRepeatedOf(resp, res) {
			continue
		}
		reqName := strings.TrimSuffix(name, "Response") + "Request"
		for _, req := range f.Messages {
			if string(req.Desc.Name()) == reqName {
				return req
			}
		}
	}
	return nil
}

func hasRepeatedOf(container, target *protogen.Message) bool {
	for _, field := range container.Fields {
		if !field.Desc.IsList() {
			continue
		}
		if field.Desc.Kind() != protoreflect.MessageKind {
			continue
		}
		if field.Message == target {
			return true
		}
	}
	return false
}

// emitOrderByFields emits a package-level `{Resource}OrderByFields` slice
// listing the AIP orderable paths on the resource, in proto declaration
// order. ParseOrderBy uses it as the allow-list.
func emitOrderByFields(g *protogen.GeneratedFile, p listPair) {
	resName := p.resource.GoIdent.GoName
	g.P("// ", resName, "OrderByFields lists the AIP orderable paths on ", resName, ",")
	g.P("// in proto declaration order.")
	g.P("var ", resName, "OrderByFields = []string{")
	for _, field := range p.orderable {
		g.P(`	"`, string(field.Desc.Name()), `",`)
	}
	g.P("}")
	g.P()
}

func emitParseOrderBy(g *protogen.GeneratedFile, p listPair) {
	reqName := p.request.GoIdent.GoName
	resName := p.resource.GoIdent.GoName

	g.P("// ParseOrderBy parses the AIP-132 `order_by` string on ", reqName, ".")
	g.P("// Rejects paths not in [", resName, "OrderByFields]. The returned error")
	g.P("// is suitable for a connect InvalidArgument response; on success the")
	g.P("// caller receives the parsed [", orderingPackage.Ident("OrderBy"), "], ready to translate")
	g.P("// into an ORDER BY clause.")
	g.P("func (x *", reqName, ") ParseOrderBy() (", orderingPackage.Ident("OrderBy"), ", error) {")
	g.P("	order, err := ", orderingPackage.Ident("ParseOrderBy"), "(x)")
	g.P("	if err != nil {")
	g.P(`		return `, orderingPackage.Ident("OrderBy"), `{}, `, fmtPackage.Ident("Errorf"), `("invalid order_by: %w", err)`)
	g.P("	}")
	g.P("	if err := order.ValidateForMessage(&", resName, "{}); err != nil {")
	g.P(`		return `, orderingPackage.Ident("OrderBy"), `{}, `, fmtPackage.Ident("Errorf"), `("invalid order_by: %w", err)`)
	g.P("	}")
	g.P("	if err := order.ValidateForPaths(", resName, "OrderByFields...); err != nil {")
	g.P(`		return `, orderingPackage.Ident("OrderBy"), `{}, `, fmtPackage.Ident("Errorf"), `("invalid order_by: %w", err)`)
	g.P("	}")
	g.P("	return order, nil")
	g.P("}")
	g.P()
}

// emitFilterDeclarations emits a package-level `{Resource}FilterDeclarations`
// var plus an `init()` that builds it exactly once at package load. Any error
// from NewDeclarations is a codegen bug (duplicate idents, bad CEL types) and
// is raised as a panic so it surfaces at program start, not on first request.
func emitFilterDeclarations(g *protogen.GeneratedFile, p listPair) error {
	resName := p.resource.GoIdent.GoName

	type decl struct {
		name string
		kind string // rendered filtering.TypeXxx reference
	}
	var decls []decl
	for _, field := range p.filterable {
		kind, err := celTypeExpr(g, field)
		if err != nil {
			return fmt.Errorf("field %q: %w", field.Desc.Name(), err)
		}
		decls = append(decls, decl{name: string(field.Desc.Name()), kind: kind})
	}

	g.P("// ", resName, "FilterDeclarations is the AIP-160 CEL declaration set for")
	g.P("// fields declared `(protoc_contrib.aip.filterable) = true` on ", resName, ".")
	g.P("var ", resName, "FilterDeclarations *", filteringPackage.Ident("Declarations"))
	g.P()
	g.P("func init() {")
	g.P("	decls, err := ", filteringPackage.Ident("NewDeclarations"), "(")
	g.P("		", filteringPackage.Ident("DeclareStandardFunctions"), "(),")
	for _, d := range decls {
		g.P(`		`, filteringPackage.Ident("DeclareIdent"), `("`, d.name, `", `, d.kind, `),`)
	}
	g.P("	)")
	g.P("	if err != nil {")
	g.P(`		panic(`, fmtPackage.Ident("Errorf"), `("protoc-gen-go-aip: `, resName, ` declarations: %w", err))`)
	g.P("	}")
	g.P("	", resName, "FilterDeclarations = decls")
	g.P("}")
	g.P()
	return nil
}

// emitQueryType emits a single package-level `Query` struct bundling the
// parsed dimensions a ParseQuery method returns. Declared once per
// generated file; the field set is the union across all pairs that have
// at least two of {filter, order_by, page_token}. Dimensions a given
// pair does not support are left zero by that pair's ParseQuery.
func emitQueryType(g *protogen.GeneratedFile, filter, orderBy, pageToken bool) {
	g.P("// Query bundles the parsed AIP dimensions for a List request.")
	g.P("// A field is the zero value when the corresponding input was empty")
	g.P("// on the inbound request, or when the request does not support that")
	g.P("// dimension.")
	g.P("type Query struct {")
	if filter {
		g.P("	Filter    ", filteringPackage.Ident("Filter"))
	}
	if orderBy {
		g.P("	OrderBy   ", orderingPackage.Ident("OrderBy"))
	}
	if pageToken {
		g.P("	PageToken ", paginationPackage.Ident("PageToken"))
	}
	g.P("}")
	g.P()

	if orderBy {
		g.P("// OrderByPaths returns the field paths from Query.OrderBy in their")
		g.P("// original order, suitable for building a fieldmaskpb.FieldMask or")
		g.P("// driving projection logic.")
		g.P("func (q Query) OrderByPaths() []string {")
		g.P("	paths := make([]string, len(q.OrderBy.Fields))")
		g.P("	for i, field := range q.OrderBy.Fields {")
		g.P("		paths[i] = field.Path")
		g.P("	}")
		g.P("	return paths")
		g.P("}")
		g.P()
	}
}

// emitParseQuery emits a ParseQuery method that composes whichever of
// ParseFilter, ParseOrderBy, and ParsePageToken the pair supports.
// The first failing dimension's error is returned verbatim, preserving
// its "invalid {dimension}" prefix for the caller to log or map.
func emitParseQuery(g *protogen.GeneratedFile, p listPair) {
	reqName := p.request.GoIdent.GoName
	hasFilter := len(p.filterable) > 0
	hasOrder := len(p.orderable) > 0
	hasToken := p.hasPageToken

	g.P("// ParseQuery parses every AIP dimension supported by ", reqName, ",")
	g.P("// applying the same validation as the per-dimension parsers. On")
	g.P("// error the first failing dimension's wrapped error is returned")
	g.P("// verbatim; map to codes.InvalidArgument at the RPC boundary.")
	g.P("func (x *", reqName, ") ParseQuery() (Query, error) {")
	if hasFilter {
		g.P("	filter, err := x.ParseFilter()")
		g.P("	if err != nil {")
		g.P("		return Query{}, err")
		g.P("	}")
	}
	if hasOrder {
		g.P("	order, err := x.ParseOrderBy()")
		g.P("	if err != nil {")
		g.P("		return Query{}, err")
		g.P("	}")
	}
	if hasToken {
		g.P("	pageToken, err := x.ParsePageToken()")
		g.P("	if err != nil {")
		g.P("		return Query{}, err")
		g.P("	}")
	}
	g.P("	return Query{")
	if hasFilter {
		g.P("		Filter:    filter,")
	}
	if hasOrder {
		g.P("		OrderBy:   order,")
	}
	if hasToken {
		g.P("		PageToken: pageToken,")
	}
	g.P("	}, nil")
	g.P("}")
	g.P()
}

// emitParsePageToken emits a thin forwarder onto pagination.ParsePageToken
// so callers get the same req.ParseXxx() ergonomic as ParseFilter /
// ParseOrderBy.
func emitParsePageToken(g *protogen.GeneratedFile, p listPair) {
	reqName := p.request.GoIdent.GoName

	g.P("// ParsePageToken decodes the AIP-158 offset `page_token` on ", reqName, "")
	g.P("// and verifies its checksum against the current request, delegating to")
	g.P("// [", paginationPackage.Ident("ParsePageToken"), "]. On the first page (page_token == \"\") it")
	g.P("// returns a zero-offset [", paginationPackage.Ident("PageToken"), "] carrying the current checksum.")
	g.P("func (x *", reqName, ") ParsePageToken() (", paginationPackage.Ident("PageToken"), ", error) {")
	g.P("	pageToken, err := ", paginationPackage.Ident("ParsePageToken"), "(x)")
	g.P("	if err != nil {")
	g.P(`		return `, paginationPackage.Ident("PageToken"), `{}, `, fmtPackage.Ident("Errorf"), `("invalid page_token: %w", err)`)
	g.P("	}")
	g.P("	return pageToken, nil")
	g.P("}")
	g.P()
}

func emitParseFilter(g *protogen.GeneratedFile, p listPair) {
	reqName := p.request.GoIdent.GoName
	resName := p.resource.GoIdent.GoName

	g.P("// ParseFilter parses the AIP-160 `filter` string on ", reqName, " against")
	g.P("// [", resName, "FilterDeclarations]. The returned error is suitable for")
	g.P("// a connect InvalidArgument response; on success the caller receives the")
	g.P("// parsed [", filteringPackage.Ident("Filter"), "], ready to translate into a WHERE clause.")
	g.P("func (x *", reqName, ") ParseFilter() (", filteringPackage.Ident("Filter"), ", error) {")
	g.P("	filter, err := ", filteringPackage.Ident("ParseFilter"), "(x, ", resName, "FilterDeclarations)")
	g.P("	if err != nil {")
	g.P(`		return `, filteringPackage.Ident("Filter"), `{}, `, fmtPackage.Ident("Errorf"), `("invalid filter: %w", err)`)
	g.P("	}")
	g.P("	return filter, nil")
	g.P("}")
	g.P()
}

// celTypeExpr renders the filtering.TypeXxx expression for the CEL type
// that matches the field's proto kind. Returns an error when the field's
// kind is not supported (nested messages other than WKT Timestamp /
// Duration, maps, and repeated fields all fall through).
func celTypeExpr(g *protogen.GeneratedFile, field *protogen.Field) (string, error) {
	if field.Desc.IsList() {
		return "", fmt.Errorf("repeated fields are not supported")
	}
	if field.Desc.IsMap() {
		return "", fmt.Errorf("map fields are not supported")
	}
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		return g.QualifiedGoIdent(filteringPackage.Ident("TypeString")), nil
	case protoreflect.BoolKind:
		return g.QualifiedGoIdent(filteringPackage.Ident("TypeBool")), nil
	case protoreflect.Int32Kind, protoreflect.Int64Kind,
		protoreflect.Sint32Kind, protoreflect.Sint64Kind,
		protoreflect.Sfixed32Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.Fixed32Kind, protoreflect.Fixed64Kind:
		return g.QualifiedGoIdent(filteringPackage.Ident("TypeInt")), nil
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return g.QualifiedGoIdent(filteringPackage.Ident("TypeFloat")), nil
	case protoreflect.EnumKind:
		enumIdent := g.QualifiedGoIdent(field.Enum.GoIdent)
		return fmt.Sprintf("%s(%s(0).Type())", g.QualifiedGoIdent(filteringPackage.Ident("TypeEnum")), enumIdent), nil
	case protoreflect.MessageKind:
		switch string(field.Message.Desc.FullName()) {
		case "google.protobuf.Timestamp":
			return g.QualifiedGoIdent(filteringPackage.Ident("TypeTimestamp")), nil
		case "google.protobuf.Duration":
			return g.QualifiedGoIdent(filteringPackage.Ident("TypeDuration")), nil
		default:
			return "", fmt.Errorf("nested message type %q is not supported", field.Message.Desc.FullName())
		}
	default:
		return "", fmt.Errorf("unsupported field kind %q", field.Desc.Kind())
	}
}
