// Package query emits CEL filtering helpers (AIP-160) on List request
// messages: a `{Request}FilterEnv` and a `ParseFilter` method.
//
// Ordering (AIP-132) and page tokens (AIP-158) are deliberately not
// generated. Both are only meaningful against the column map, ordering and
// SQL that actually run, which the .proto cannot see, so they belong to the
// query layer. protoc-gen-rust-aip generates nothing for them either. See
// https://github.com/protoc-contrib/protoc-gen-go-aip/issues/45.
//
// A request is a List request when a service method takes it and returns a
// message with a single repeated message field; that field's type is the
// resource, and its fields are what the helpers expose. Nothing needs
// annotating — the same derivation the OpenAPI generator performs on a
// List*Response schema.
package query

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Suffix is `_aip.pb.query.go`. The leading `_` (0x5F) sorts after `.`
// (0x2E), so `<name>.pb.go` always initialises before our companion —
// descriptor init runs before `init()` references enum types. The
// `_aip.` prefix also groups all AIP-family plugin output together
// (`_aip.pb.resource.go`, etc.) regardless of the trailing suffix.
const generatedFilenameSuffix = "_aip.pb.query.go"

var (
	fmtPackage = protogen.GoImportPath("fmt")
	celPackage = protogen.GoImportPath("cel.dev/cel-go/cel")
)

// Generate walks every file scheduled for generation and emits a
// `_aip.pb.query.go` companion for each file containing at least one
// List request carrying a `filter` field.
func Generate(plugin *protogen.Plugin) error {
	for _, f := range plugin.Files {
		if !f.Generate {
			continue
		}
		if err := generateFile(plugin, f); err != nil {
			return err
		}
	}
	return nil
}

func generateFile(plugin *protogen.Plugin, f *protogen.File) error {
	resources := resourceByRequest(f)
	var requests []requestInfo
	for _, m := range f.Messages {
		info, err := analyzeRequest(m, resources[m])
		if err != nil {
			return fmt.Errorf("%s: %w", m.Desc.FullName(), err)
		}
		if info == nil {
			continue
		}
		requests = append(requests, *info)
	}
	if len(requests) == 0 {
		return nil
	}

	g := plugin.NewGeneratedFile(
		f.GeneratedFilenamePrefix+generatedFilenameSuffix,
		f.GoImportPath,
	)
	g.P("// Code generated by protoc-gen-go-aip. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package ", f.GoPackageName)
	g.P()

	for _, r := range requests {
		if err := emitFilterDeclarations(g, r); err != nil {
			return fmt.Errorf("%s: %w", r.request.GoIdent.GoName, err)
		}
		emitParseFilter(g, r)
	}
	return nil
}

type requestInfo struct {
	request *protogen.Message
	filter  *filterAnalysis
}

type filterAnalysis struct {
	resource *protogen.Message
	fields   []*protogen.Field
}

// analyzeRequest derives the filterable surface of req from resource — the
// message the corresponding List method returns. It returns nil when req has
// no `filter` string field or the resource has no field with a CEL type.
//
// Every resource field that maps to a CEL type is declared; there is no
// per-request allow-list. The gate on what a client may actually filter by
// is the AIP-path to DB-column map handed to the query layer, which
// is fail-closed and lives next to the schema that knows which columns exist
// and which are indexed. A second allow-list in the .proto would only be a
// copy of it, free to drift.
func analyzeRequest(req, resource *protogen.Message) (*requestInfo, error) {
	if resource == nil {
		return nil, nil
	}
	for _, field := range req.Fields {
		if !isQueryStringField(field) || field.Desc.Name() != "filter" {
			continue
		}
		fields, err := queryableFields(resource)
		if err != nil {
			return nil, fmt.Errorf("filter: %w", err)
		}
		if len(fields) == 0 {
			return nil, nil
		}
		return &requestInfo{
			request: req,
			filter:  &filterAnalysis{resource: resource, fields: fields},
		}, nil
	}
	return nil, nil
}

// queryableFields returns the fields of resource that have a CEL type, in
// declaration order. Fields with no scalar reading — nested messages other
// than the well-known wrappers, repeated fields and maps — have no total
// order and cannot be compared, so they are skipped rather than rejected.
func queryableFields(resource *protogen.Message) ([]*protogen.Field, error) {
	fields := make([]*protogen.Field, 0, len(resource.Fields))
	for _, field := range resource.Fields {
		if field.Desc.IsList() || field.Desc.IsMap() {
			continue
		}
		if !hasCELType(field) {
			continue
		}
		fields = append(fields, field)
	}
	return fields, nil
}

// resourceByRequest maps each List request message to the resource its
// method returns, by taking the sole repeated message field of the response.
//
// This mirrors how the OpenAPI generator reads a List*Response schema, so
// both surfaces declare the same variables for the same resource.
func resourceByRequest(f *protogen.File) map[*protogen.Message]*protogen.Message {
	out := make(map[*protogen.Message]*protogen.Message)
	for _, service := range f.Services {
		for _, method := range service.Methods {
			if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
				continue
			}
			if resource := repeatedResourceOf(method.Output); resource != nil {
				out[method.Input] = resource
			}
		}
	}
	return out
}

// repeatedResourceOf returns the resource carried by a List response: its
// single repeated message field. A response with none, or with more than
// one, is not a List response and yields nil.
func repeatedResourceOf(response *protogen.Message) *protogen.Message {
	var found *protogen.Message
	for _, field := range response.Fields {
		if !field.Desc.IsList() || field.Message == nil || field.Desc.IsMap() {
			continue
		}
		if found != nil {
			return nil // ambiguous
		}
		found = field.Message
	}
	return found
}

func isQueryStringField(field *protogen.Field) bool {
	return field.Desc.Kind() == protoreflect.StringKind && !field.Desc.IsList()
}

// prefixOf strips the conventional `Request` suffix to produce the
// per-request identifier prefix (e.g. `ListBooksRequest` →
// `ListBooks`). Falls back to the full Go name when absent.
func prefixOf(req *protogen.Message) string {
	return strings.TrimSuffix(req.GoIdent.GoName, "Request")
}

// emitFilterDeclarations emits a package-level `{Request}FilterDeclarations`
// var plus an `init()` that builds it exactly once at package load. Any
// error from NewDeclarations is a codegen bug (duplicate idents, bad CEL
// types) and is raised as a panic so it surfaces at program start, not on
// first request.
func emitFilterDeclarations(g *protogen.GeneratedFile, r requestInfo) error {
	prefix := prefixOf(r.request)

	type decl struct {
		name string
		kind string
	}
	var decls []decl
	for _, field := range r.filter.fields {
		kind, err := celTypeExpr(g, field)
		if err != nil {
			return fmt.Errorf("field %q: %w", field.Desc.Name(), err)
		}
		decls = append(decls, decl{name: string(field.Desc.Name()), kind: kind})
	}

	g.P("// ", prefix, "FilterEnv is the CEL environment used to compile `filter`")
	g.P("// expressions on ", r.request.GoIdent.GoName, ". It declares every field of")
	g.P("// ", r.filter.resource.GoIdent.GoName, " that has a CEL type; which of them a client may")
	g.P("// actually query is gated by the column map at the query layer.")
	g.P("var ", prefix, "FilterEnv *", celPackage.Ident("Env"))
	g.P()
	g.P("func init() {")
	g.P("	env, err := ", celPackage.Ident("NewEnv"), "(")
	for _, d := range decls {
		g.P(`		`, celPackage.Ident("Variable"), `("`, d.name, `", `, d.kind, `),`)
	}
	g.P("	)")
	g.P("	if err != nil {")
	g.P(`		panic(`, fmtPackage.Ident("Errorf"), `("protoc-gen-go-aip: `, prefix, ` filter env: %w", err))`)
	g.P("	}")
	g.P("	", prefix, "FilterEnv = env")
	g.P("}")
	g.P()
	return nil
}

func emitParseFilter(g *protogen.GeneratedFile, r requestInfo) {
	reqName := r.request.GoIdent.GoName
	prefix := prefixOf(r.request)

	g.P("// ParseFilter compiles the CEL `filter` expression on ", reqName, " against")
	g.P("// [", prefix, "FilterEnv]. It returns (nil, nil) when no filter was")
	g.P("// provided. The returned error is suitable for a connect InvalidArgument")
	g.P("// response; the *cel.Ast can be passed straight to pgxcel.Transpile.")
	g.P("func (x *", reqName, ") ParseFilter() (*", celPackage.Ident("Ast"), ", error) {")
	g.P(`	if x.GetFilter() == "" {`)
	g.P("		return nil, nil")
	g.P("	}")
	g.P("	ast, issues := ", prefix, "FilterEnv.Compile(x.GetFilter())")
	g.P("	if err := issues.Err(); err != nil {")
	g.P(`		return nil, `, fmtPackage.Ident("Errorf"), `("invalid filter: %w", err)`)
	g.P("	}")
	g.P("	return ast, nil")
	g.P("}")
	g.P()
}

// celType returns the cel-go type identifier matching the field's proto
// kind, and whether the field has one at all.
//
// Fields with no total order — nested messages other than the well-known
// Timestamp and Duration, maps, and repeated fields — have none, and cannot
// appear in a filter.
func celType(field *protogen.Field) (protogen.GoIdent, bool) {
	if field.Desc.IsList() || field.Desc.IsMap() {
		return protogen.GoIdent{}, false
	}
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		return celPackage.Ident("StringType"), true
	case protoreflect.BoolKind:
		return celPackage.Ident("BoolType"), true
	case protoreflect.Int32Kind, protoreflect.Int64Kind,
		protoreflect.Sint32Kind, protoreflect.Sint64Kind,
		protoreflect.Sfixed32Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.Fixed32Kind, protoreflect.Fixed64Kind:
		return celPackage.Ident("IntType"), true
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return celPackage.Ident("DoubleType"), true
	case protoreflect.EnumKind:
		// CEL models proto enums as integers, which is also how a database
		// column stores them, so an enum compares against its number.
		return celPackage.Ident("IntType"), true
	case protoreflect.MessageKind:
		switch string(field.Message.Desc.FullName()) {
		case "google.protobuf.Timestamp":
			return celPackage.Ident("TimestampType"), true
		case "google.protobuf.Duration":
			return celPackage.Ident("DurationType"), true
		}
	}
	return protogen.GoIdent{}, false
}

// hasCELType reports whether field can appear in a filter.
func hasCELType(field *protogen.Field) bool {
	_, ok := celType(field)
	return ok
}

// celTypeExpr renders the cel.XxxType expression for field, qualified for
// the file being generated.
func celTypeExpr(g *protogen.GeneratedFile, field *protogen.Field) (string, error) {
	ident, ok := celType(field)
	if !ok {
		return "", fmt.Errorf("field %q has no CEL type", field.Desc.Name())
	}
	return g.QualifiedGoIdent(ident), nil
}
