// v2 of an API that declares the same resource types as its other version.
// Each version's references, parents and create requests must bind to its
// own declarations: only v2 types Shelf's ID as a UUID, so a v1 type bound to
// v2's (or the reverse) would not compile.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: versions/v2/library.proto

package v2

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shelf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shelf) Reset() {
	*x = Shelf{}
	mi := &file_versions_v2_library_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shelf) ProtoMessage() {}

func (x *Shelf) ProtoReflect() protoreflect.Message {
	mi := &file_versions_v2_library_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shelf.ProtoReflect.Descriptor instead.
func (*Shelf) Descriptor() ([]byte, []int) {
	return file_versions_v2_library_proto_rawDescGZIP(), []int{0}
}

func (x *Shelf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shelf         string                 `protobuf:"bytes,2,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_versions_v2_library_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_versions_v2_library_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_versions_v2_library_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetShelf() string {
	if x != nil {
		return x.Shelf
	}
	return ""
}

type CreateShelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         *Shelf                 `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	ShelfId       string                 `protobuf:"bytes,2,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShelfRequest) Reset() {
	*x = CreateShelfRequest{}
	mi := &file_versions_v2_library_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfRequest) ProtoMessage() {}

func (x *CreateShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_versions_v2_library_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShelfRequest.ProtoReflect.Descriptor instead.
func (*CreateShelfRequest) Descriptor() ([]byte, []int) {
	return file_versions_v2_library_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShelfRequest) GetShelf() *Shelf {
	if x != nil {
		return x.Shelf
	}
	return nil
}

func (x *CreateShelfRequest) GetShelfId() string {
	if x != nil {
		return x.ShelfId
	}
	return ""
}

var File_versions_v2_library_proto protoreflect.FileDescriptor

const file_versions_v2_library_proto_rawDesc = "" +
	"\n" +
	"\x19versions/v2/library.proto\x12\x11tests.versions.v2\x1a\x1bgoogle/api/field_info.proto\x1a\x19google/api/resource.proto\"M\n" +
	"\x05Shelf\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:0\xeaA-\n" +
	"\x1aversions.example.com/Shelf\x12\x0fshelves/{shelf}\"\x8f\x01\n" +
	"\x04Book\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\x05shelf\x18\x02 \x01(\tB\x1f\xfaA\x1c\n" +
	"\x1aversions.example.com/ShelfR\x05shelf:<\xeaA9\n" +
	"\x19versions.example.com/Book\x12\x1cshelves/{shelf}/books/{book}\"i\n" +
	"\x12CreateShelfRequest\x12.\n" +
	"\x05shelf\x18\x01 \x01(\v2\x18.tests.versions.v2.ShelfR\x05shelf\x12#\n" +
	"\bshelf_id\x18\x02 \x01(\tB\b\xe2\x8c\xcf\xd7\b\x02\b\x01R\ashelfIdB\\ZZgithub.com/protoc-contrib/protoc-gen-go-aip/internal/generator/resource/testpb/versions/v2b\x06proto3"

var (
	file_versions_v2_library_proto_rawDescOnce sync.Once
	file_versions_v2_library_proto_rawDescData []byte
)

func file_versions_v2_library_proto_rawDescGZIP() []byte {
	file_versions_v2_library_proto_rawDescOnce.Do(func() {
		file_versions_v2_library_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_versions_v2_library_proto_rawDesc), len(file_versions_v2_library_proto_rawDesc)))
	})
	return file_versions_v2_library_proto_rawDescData
}

var file_versions_v2_library_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_versions_v2_library_proto_goTypes = []any{
	(*Shelf)(nil),              // 0: tests.versions.v2.Shelf
	(*Book)(nil),               // 1: tests.versions.v2.Book
	(*CreateShelfRequest)(nil), // 2: tests.versions.v2.CreateShelfRequest
}
var file_versions_v2_library_proto_depIdxs = []int32{
	0, // 0: tests.versions.v2.CreateShelfRequest.shelf:type_name -> tests.versions.v2.Shelf
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_versions_v2_library_proto_init() }
func file_versions_v2_library_proto_init() {
	if File_versions_v2_library_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_versions_v2_library_proto_rawDesc), len(file_versions_v2_library_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_versions_v2_library_proto_goTypes,
		DependencyIndexes: file_versions_v2_library_proto_depIdxs,
		MessageInfos:      file_versions_v2_library_proto_msgTypes,
	}.Build()
	File_versions_v2_library_proto = out.File
	file_versions_v2_library_proto_goTypes = nil
	file_versions_v2_library_proto_depIdxs = nil
}
