// Field options consumed by protoc-gen-go-aip-query to drive List-method
// codegen for AIP-132 (ordering) and AIP-160 (filtering).
//
// Annotate fields on a message that carries `google.api.resource`. The
// plugin finds the matching `List{Plural}Request` (by inspecting the
// `repeated {Resource}` field on `List{Plural}Response`) and emits
// per-request ParseOrderBy / ParseFilter methods plus per-resource
// package-level vars ({Resource}OrderByPaths, {Resource}FilterDeclarations)
// that the methods reference.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protoc_contrib/aip/query.proto

package aip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_protoc_contrib_aip_query_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "protoc_contrib.aip.orderable",
		Tag:           "varint,50001,opt,name=orderable",
		Filename:      "protoc_contrib/aip/query.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "protoc_contrib.aip.filterable",
		Tag:           "varint,50002,opt,name=filterable",
		Filename:      "protoc_contrib/aip/query.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50003,
		Name:          "protoc_contrib.aip.column",
		Tag:           "bytes,50003,opt,name=column",
		Filename:      "protoc_contrib/aip/query.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// When true on a resource field, it may appear in
	// `List{Resource}Request.order_by` (AIP-132). The plugin emits the
	// field's proto name into {Resource}OrderByFields.
	//
	// optional bool orderable = 50001;
	E_Orderable = &file_protoc_contrib_aip_query_proto_extTypes[0]
	// When true on a resource field, it may appear in
	// `List{Resource}Request.filter` (AIP-160). The plugin emits a
	// `filtering.Declarations` entry with the CEL type inferred from the
	// field's kind into {Resource}FilterDeclarations.
	//
	// optional bool filterable = 50002;
	E_Filterable = &file_protoc_contrib_aip_query_proto_extTypes[1]
	// Overrides the backing DB column name exposed in the generated
	// {Resource}Columns map. Only meaningful when the field is also
	// annotated orderable and/or filterable; otherwise the field is
	// absent from the map. When unset, callers should fall back to
	// the proto field name.
	//
	// optional string column = 50003;
	E_Column = &file_protoc_contrib_aip_query_proto_extTypes[2]
)

var File_protoc_contrib_aip_query_proto protoreflect.FileDescriptor

const file_protoc_contrib_aip_query_proto_rawDesc = "" +
	"\n" +
	"\x1eprotoc_contrib/aip/query.proto\x12\x12protoc_contrib.aip\x1a google/protobuf/descriptor.proto:=\n" +
	"\torderable\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\bR\torderable:?\n" +
	"\n" +
	"filterable\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\bR\n" +
	"filterable:7\n" +
	"\x06column\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x01(\tR\x06columnBJZHgithub.com/protoc-contrib/protoc-gen-go-aip-query/protoc_contrib/aip;aipb\x06proto3"

var file_protoc_contrib_aip_query_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_protoc_contrib_aip_query_proto_depIdxs = []int32{
	0, // 0: protoc_contrib.aip.orderable:extendee -> google.protobuf.FieldOptions
	0, // 1: protoc_contrib.aip.filterable:extendee -> google.protobuf.FieldOptions
	0, // 2: protoc_contrib.aip.column:extendee -> google.protobuf.FieldOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_contrib_aip_query_proto_init() }
func file_protoc_contrib_aip_query_proto_init() {
	if File_protoc_contrib_aip_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_contrib_aip_query_proto_rawDesc), len(file_protoc_contrib_aip_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_protoc_contrib_aip_query_proto_goTypes,
		DependencyIndexes: file_protoc_contrib_aip_query_proto_depIdxs,
		ExtensionInfos:    file_protoc_contrib_aip_query_proto_extTypes,
	}.Build()
	File_protoc_contrib_aip_query_proto = out.File
	file_protoc_contrib_aip_query_proto_goTypes = nil
	file_protoc_contrib_aip_query_proto_depIdxs = nil
}
