// Field option consumed by protoc-gen-go-aip to drive AIP query codegen.
//
// Annotate a request field with `(protoc_contrib.aip.field_reference)`
// pointing at a resource type and the subset of its fields exposed in
// that context. The carrying field's name determines what the plugin
// emits:
//
//   filter   (string, AIP-160) → {Request}FilterDeclarations + ParseFilter
//   order_by (string, AIP-132) → {Request}OrderByFields      + ParseOrderBy
//
// Other field names are reserved for future contexts (read_mask,
// update_mask, …) and are silently ignored today.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protoc_contrib/aip/query.proto

package aip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldReference points at a subset of a resource's fields. The carrying
// field's name decides how the plugin interprets the list (see file
// header).
type FieldReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AIP resource type, e.g. "library.googleapis.com/Book". Must match
	// the `type` value of a `(google.api.resource)` annotation on a
	// message in the compilation unit.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Names of fields on the referenced resource exposed in this context.
	Fields        []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldReference) Reset() {
	*x = FieldReference{}
	mi := &file_protoc_contrib_aip_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldReference) ProtoMessage() {}

func (x *FieldReference) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_contrib_aip_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldReference.ProtoReflect.Descriptor instead.
func (*FieldReference) Descriptor() ([]byte, []int) {
	return file_protoc_contrib_aip_query_proto_rawDescGZIP(), []int{0}
}

func (x *FieldReference) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldReference) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var file_protoc_contrib_aip_query_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldReference)(nil),
		Field:         50001,
		Name:          "protoc_contrib.aip.field_reference",
		Tag:           "bytes,50001,opt,name=field_reference",
		Filename:      "protoc_contrib/aip/query.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional protoc_contrib.aip.FieldReference field_reference = 50001;
	E_FieldReference = &file_protoc_contrib_aip_query_proto_extTypes[0]
)

var File_protoc_contrib_aip_query_proto protoreflect.FileDescriptor

const file_protoc_contrib_aip_query_proto_rawDesc = "" +
	"\n" +
	"\x1eprotoc_contrib/aip/query.proto\x12\x12protoc_contrib.aip\x1a google/protobuf/descriptor.proto\"<\n" +
	"\x0eFieldReference\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields:l\n" +
	"\x0ffield_reference\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\v2\".protoc_contrib.aip.FieldReferenceR\x0efieldReferenceBDZBgithub.com/protoc-contrib/protoc-gen-go-aip/protoc_contrib/aip;aipb\x06proto3"

var (
	file_protoc_contrib_aip_query_proto_rawDescOnce sync.Once
	file_protoc_contrib_aip_query_proto_rawDescData []byte
)

func file_protoc_contrib_aip_query_proto_rawDescGZIP() []byte {
	file_protoc_contrib_aip_query_proto_rawDescOnce.Do(func() {
		file_protoc_contrib_aip_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoc_contrib_aip_query_proto_rawDesc), len(file_protoc_contrib_aip_query_proto_rawDesc)))
	})
	return file_protoc_contrib_aip_query_proto_rawDescData
}

var file_protoc_contrib_aip_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protoc_contrib_aip_query_proto_goTypes = []any{
	(*FieldReference)(nil),            // 0: protoc_contrib.aip.FieldReference
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_protoc_contrib_aip_query_proto_depIdxs = []int32{
	1, // 0: protoc_contrib.aip.field_reference:extendee -> google.protobuf.FieldOptions
	0, // 1: protoc_contrib.aip.field_reference:type_name -> protoc_contrib.aip.FieldReference
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_contrib_aip_query_proto_init() }
func file_protoc_contrib_aip_query_proto_init() {
	if File_protoc_contrib_aip_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_contrib_aip_query_proto_rawDesc), len(file_protoc_contrib_aip_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_protoc_contrib_aip_query_proto_goTypes,
		DependencyIndexes: file_protoc_contrib_aip_query_proto_depIdxs,
		MessageInfos:      file_protoc_contrib_aip_query_proto_msgTypes,
		ExtensionInfos:    file_protoc_contrib_aip_query_proto_extTypes,
	}.Build()
	File_protoc_contrib_aip_query_proto = out.File
	file_protoc_contrib_aip_query_proto_goTypes = nil
	file_protoc_contrib_aip_query_proto_depIdxs = nil
}
